################ Inclusao de tabela de extrato 

CREATE TABLE `FIN_EXTRATO` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `PESSOA` int(11) DEFAULT NULL,
  `PESSOAFORNECEDOR` int(11) DEFAULT NULL,
  `TIPOLANCAMENTO` char(1) NOT NULL,
  `SITUACAOLANCAMENTO` char(1) NOT NULL DEFAULT 'A',
  `LANCAMENTO` timestamp NOT NULL DEFAULT current_timestamp(),
  `COMPETENCIA` date NOT NULL,
  `GENERO` varchar(10) NOT NULL,
  `CENTROCUSTO` int(11) NOT NULL,
  `VALOR` decimal(11,2) DEFAULT 0.00,
  `OBS` text NOT NULL,
  `IDFIN` int(11) DEFAULT NULL,
  `USERINSERT` int(11) DEFAULT NULL,
  `DATEINSERT` timestamp NULL DEFAULT NULL,
  `USERCHANGE` int(11) DEFAULT NULL,
  `DATECHANGE` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`ID`)
);

################# Inclusao status de extrato 

INSERT INTO AMB_DDM
(ALIAS, NRCAMPO, CAMPO, TIPO, TAMANHO, DECIMAIS, FORMATO, REQUERIDO, PADRAO, LEGENDA, MASCARA, NOMEEXTERNO, ALTERACAO, DESCRICAO, `SQL`, MENSAGEM, MENU)
VALUES('FIN_MENU', 28, 'SITUACAOPGTO', 'E', 0, 0, NULL, 'N', 'E - EXTRATO', NULL, NULL, NULL, '2010-02-18', NULL, NULL, NULL, NULL);


################ Inclusao de condicao de pagamento no extrato

INSERT INTO FAT_COND_PGTO (ID, DESCRICAO, FORMAPGTO, NUMPARCELAS, SITUACAOLCTO) VALUES ('618', 'CARTEIRA INTERNA', '0', '1', 'E');

