-- =====================================================
-- ALTERAÇÕES NECESSÁRIAS PARA ATUALIZAR BANCO ADM v4.5
-- =====================================================
-- Data: $(date)
-- Versão: 4.5
-- Descrição: Script de alterações para bancos existentes
-- =====================================================

-- 1. ADICIONAR CAMPO BLOQUEADO NA TABELA FAT_COND_PGTO
-- =====================================================
ALTER TABLE `FAT_COND_PGTO` 
ADD COLUMN `BLOQUEADO` char(1) NOT NULL DEFAULT 'A' AFTER `SITUACAOLCTO`;

-- 2. ALTERAR TABELA EST_GRUPO PARA AUTO_INCREMENT E ADICIONAR CAMPOS DE AUDITORIA
-- =====================================================
-- Primeiro, criar tabela temporária com nova estrutura
CREATE TABLE `EST_GRUPO_NEW` (  
  `ID` int NOT NULL AUTO_INCREMENT,
  `GRUPO` varchar(15) NOT NULL DEFAULT '',
  `DESCRICAO` varchar(40) NOT NULL,
  `TIPO` char(1) NOT NULL,
  `NIVEL` smallint NOT NULL,
  `COMISSAOVENDAS` decimal(5,2) DEFAULT NULL,
  `USERINSERT` int DEFAULT NULL,
  `DATEINSERT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `USERCHANGE` int DEFAULT NULL,
  `DATECHANGE` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb3;

-- Copiar dados existentes (ajustar conforme necessário)
INSERT INTO `EST_GRUPO_NEW` (`GRUPO`,`DESCRICAO`, `TIPO`, `NIVEL`)
SELECT `GRUPO`, `DESCRICAO`, `TIPO`, `NIVEL` FROM `EST_GRUPO`;

-- Remover tabela antiga e renomear nova
DROP TABLE `EST_GRUPO`;
RENAME TABLE `EST_GRUPO_NEW` TO `EST_GRUPO`;

-- 3. ADICIONAR TABELA EST_PRODUTO_EQUIVALENCIA
-- =====================================================
CREATE TABLE `EST_PRODUTO_EQUIVALENCIA` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `IDPRODUTO` int NOT NULL,
  `CODEQUIVALENTE` varchar(25) DEFAULT NULL,
  `CONTA` int DEFAULT NULL,
  `NFULTIMACOMPRA` int DEFAULT NULL,
  `DATAULTIMACOMPRA` date DEFAULT NULL,
  `QUANTULTIMACOMPRA` int DEFAULT NULL,
  `USERINSERT` int DEFAULT NULL,
  `DATEINSERT` timestamp NULL DEFAULT NULL,
  `USERCHANGE` int DEFAULT NULL,
  `DATECHANGE` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `CODFAB` (`IDPRODUTO`,`CODEQUIVALENTE`)
) ENGINE=InnoDB AUTO_INCREMENT=36639 DEFAULT CHARSET=utf8mb3;



-- 4. ADICIONAR CAMPO OBRA_ID NA TABELA FAT_PEDIDO
-- =====================================================
ALTER TABLE `FAT_PEDIDO` 
ADD COLUMN `OBRA_ID` int DEFAULT NULL AFTER `OS`;

-- 5. ADICIONAR CAMPO OBSSERVICO E ALTERAR UNIDADE NA TABELA FAT_PEDIDO_SERVICO
-- =====================================================
-- Adicionar campo OBSSERVICO
ALTER TABLE `FAT_PEDIDO_SERVICO`
ADD COLUMN `OBSSERVICO` text AFTER `DESCSERVICO`;

--IVEMAR
DROP TABLE `FAT_PEDIDO_SERVICO`;
CREATE TABLE `FAT_PEDIDO_SERVICO` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `FAT_PEDIDO_ID` int NOT NULL,
  `ID_USER` int NOT NULL,
  `DATA` date DEFAULT NULL,
  `HORAINI` time DEFAULT NULL,
  `HORAFIM` time DEFAULT NULL,
  `HORATOTAL` time DEFAULT NULL,
  `CUSTOUSER` decimal(9,2) DEFAULT NULL,
  `DESCSERVICO` mediumtext COLLATE utf8mb4_unicode_ci,
  `OBSSERVICO` mediumtext COLLATE utf8mb4_unicode_ci,
  `UNIDADE` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `QUANTIDADE` decimal(9,2) DEFAULT NULL,
  `VALUNITARIO` decimal(9,2) DEFAULT NULL,
  `TOTALSERVICO` decimal(9,2) DEFAULT NULL,
  `CAT_SERVICOS_ID` int NOT NULL,
  `CREATED_USER` int DEFAULT NULL,
  `UPDATED_USER` int DEFAULT NULL,
  `CREATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `UPDATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `fk_FAT_PEDIDO_SERVICO_FAT_PEDIDO1_idx` (`FAT_PEDIDO_ID`),
  KEY `fk_FAT_PEDIDO_SERVICO_CAT_SERVICOS1_idx` (`CAT_SERVICOS_ID`),
  CONSTRAINT `fk_FAT_PEDIDO_SERVICO_CAT_SERVICOS1` FOREIGN KEY (`CAT_SERVICOS_ID`) REFERENCES `CAT_SERVICO` (`ID`),
  CONSTRAINT `fk_FAT_PEDIDO_SERVICO_FAT_PEDIDO1` FOREIGN KEY (`FAT_PEDIDO_ID`) REFERENCES `FAT_PEDIDO` (`ID`)
);

-- Alterar campo UNIDADE para suportar mais caracteres e UTF-8 completo
ALTER TABLE `FAT_PEDIDO_SERVICO` 
MODIFY COLUMN `UNIDADE` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL;

-- Alterar a tabela para usar UTF-8 completo
ALTER TABLE `FAT_PEDIDO_SERVICO` 
CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- 6. CRIAR TABELA FIN_CLIENTE_OBRA
-- =====================================================
CREATE TABLE `FIN_CLIENTE_OBRA` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `CNO` varchar(20) DEFAULT '0',
  `PROJETO` varchar(90) DEFAULT '0',
  `RESPONSAVEL_TECNICO` int DEFAULT '0',
  `CREA` varchar(20) DEFAULT NULL,
  `ART` varchar(20) DEFAULT NULL,
  `CLIENTE` int NOT NULL,
  `STATUS` char(1) NOT NULL DEFAULT 'A' COMMENT 'A-Ativo, I-Inativo',
  `USERINSERT` int DEFAULT NULL,
  `DATEINSERT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `USERCHANGE` int DEFAULT NULL,
  `DATECHANGE` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb3;

-- 7. CRIAR TABELA FIN_CLIENTE_ENDERECO
-- =====================================================
CREATE TABLE `FIN_CLIENTE_ENDERECO` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `CLIENTE` int NOT NULL,
  `DESCRICAO` varchar(35) NOT NULL,
  `TIPOEND` varchar(15) DEFAULT 'RUA',
  `TITULOEND` varchar(15) DEFAULT NULL,
  `ENDERECO` varchar(60) DEFAULT 'SEM ENDERECO',
  `NUMERO` varchar(7) DEFAULT 'S/N',
  `COMPLEMENTO` varchar(15) DEFAULT NULL,
  `BAIRRO` varchar(20) DEFAULT NULL,
  `CIDADE` varchar(40) DEFAULT 'SEM CIDADE',
  `UF` varchar(2) DEFAULT 'PR',
  `CEP` int DEFAULT NULL,
  `HORARIO` time DEFAULT NULL,
  `FONEAREA` varchar(4) DEFAULT NULL,
  `FONE` varchar(9) DEFAULT NULL,
  `FONERAMAL` varchar(4) DEFAULT NULL,
  `FONECONTATO` varchar(15) DEFAULT NULL,
  `ENDENTREGAPADRAO` char(1) DEFAULT 'N',
  `ENDRETIRADAPADRAO` char(1) DEFAULT 'N',
  `PAIS` varchar(3) DEFAULT NULL,
  `STATUS` char(1) DEFAULT 'A',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb3;

-- 8. CRIAR TABELA AMB_LOG
-- =====================================================
CREATE TABLE `AMB_LOG` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `ID_TABLE` int NOT NULL,
  `OPERACAO` varchar(10) COLLATE utf8mb3_bin DEFAULT NULL,
  `TABELA` varchar(20) COLLATE utf8mb3_bin DEFAULT NULL,
  `SQLSAVE` text COLLATE utf8mb3_bin,
  `USERINSERT` int DEFAULT NULL,
  `DATEINSERT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_bin;

-- admsis_modena.AMB_LOG_EMAIL definição

CREATE TABLE `AMB_LOG_EMAIL` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `NUMERO_NOTA` varchar(20) DEFAULT NULL,
  `ID_NOTA` int DEFAULT NULL,
  `USUARIO` varchar(100) DEFAULT NULL,
  `ERRO` text,
  `DATA_HORA` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
);


-- 9. CRIAR TABELA AMB_EQUIPE
-- =====================================================
CREATE TABLE `AMB_EQUIPE` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `DESCRICAO` varchar(100) NOT NULL,
  `COR_EQUIPE` varchar(50) NOT NULL COMMENT 'COR DE IDENTIFICAÇÃO DA EQUIPE',
  `CREATED_USER` int NOT NULL COMMENT 'USUÁRIO QUE CRIOU O REGISTRO',
  `UPDATED_USER` int DEFAULT NULL COMMENT 'USUÁRIO QUE ATUALIZOU O REGISTRO',
  `CREATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'DATA DE CRIAÇÃO',
  `UPDATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'DATA DE ATUALIZAÇÃO',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_AMB_EQUIPE_DESCRICAO` (`DESCRICAO`)
);

-- 10. CRIAR TABELA CAT_AT_EQUIPE_USUARIO
-- =====================================================
CREATE TABLE `CAT_AT_EQUIPE_USUARIO` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `ID_EQUIPE` int NOT NULL,
  `ID_USUARIO` int NOT NULL,
  `CAT_ATENDIMENTO_ID` int NOT NULL,
  `CREATED_USER` int NOT NULL COMMENT 'USUÁRIO QUE CRIOU O REGISTRO',
  `UPDATED_USER` int DEFAULT NULL COMMENT 'USUÁRIO QUE ATUALIZOU O REGISTRO',
  `CREATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'DATA DE CRIAÇÃO',
  `UPDATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'DATA DE ATUALIZAÇÃO',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_AT_EQUIPE_USUARIO_ATENDIMENTO` (`ID_EQUIPE`,`ID_USUARIO`,`CAT_ATENDIMENTO_ID`),
  KEY `CAT_ATENDIMENTO_ID` (`CAT_ATENDIMENTO_ID`),
  CONSTRAINT `CAT_AT_EQUIPE_USUARIO_ibfk_1` FOREIGN KEY (`ID_EQUIPE`) REFERENCES `AMB_EQUIPE` (`ID`) ON DELETE CASCADE,
  CONSTRAINT `CAT_AT_EQUIPE_USUARIO_ibfk_2` FOREIGN KEY (`CAT_ATENDIMENTO_ID`) REFERENCES `CAT_ATENDIMENTO` (`ID`) ON DELETE CASCADE
);

-- admsis_concreta.CAT_AT_SERVICOS definição

CREATE TABLE `CAT_AT_SERVICOS` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `ID_USER` int NOT NULL,
  `DATA` date DEFAULT NULL,
  `HORAINI` time DEFAULT NULL,
  `HORAFIM` time DEFAULT NULL,
  `HORATOTAL` time DEFAULT NULL,
  `CUSTOUSER` decimal(9,2) DEFAULT NULL,
  `DESCSERVICO` text,
  `UNIDADE` varchar(3) DEFAULT NULL,
  `QUANTIDADE` decimal(9,2) DEFAULT NULL,
  `QUANTIDADE_EXECUTADA` decimal(9,2) DEFAULT NULL,
  `VALUNITARIO` decimal(9,2) DEFAULT NULL,
  `TOTALSERVICO` decimal(9,2) DEFAULT NULL,
  `CAT_ATENDIMENTO_ID` int NOT NULL,
  `CAT_SERVICOS_ID` int NOT NULL,
  `CREATED_USER` int DEFAULT NULL,
  `UPDATED_USER` int DEFAULT NULL,
  `CREATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `UPDATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `fk_CAT_AT_SERVICOS_CAT_ATENDIMENTO1_idx` (`CAT_ATENDIMENTO_ID`),
  KEY `fk_CAT_AT_SERVICOS_CAT_SERVICOS1_idx` (`CAT_SERVICOS_ID`),
  CONSTRAINT `fk_CAT_AT_SERVICOS_CAT_ATENDIMENTO1` FOREIGN KEY (`CAT_ATENDIMENTO_ID`) REFERENCES `CAT_ATENDIMENTO` (`ID`),
  CONSTRAINT `fk_CAT_AT_SERVICOS_CAT_SERVICOS1` FOREIGN KEY (`CAT_SERVICOS_ID`) REFERENCES `CAT_SERVICO` (`ID`)
);

-- 11. ADICIONAR CAMPOS ADICIONAIS NA TABELA CAT_AT_SERVICOS
-- =====================================================
ALTER TABLE `CAT_AT_SERVICOS` 
ADD COLUMN `QUANTIDADE_EXECUTADA` decimal(9,2) DEFAULT NULL AFTER `QUANTIDADE`;

-- 12. ADICIONAR CAMPOS ADICIONAIS NA TABELA FAT_PEDIDO_SERVICO
-- =====================================================
ALTER TABLE `FAT_PEDIDO_SERVICO` 
ADD COLUMN `QTD_CONTRATADA` decimal(9,2) DEFAULT NULL AFTER `UPDATED_AT`,
ADD COLUMN `QTD_EXECUTADA` decimal(9,2) DEFAULT NULL AFTER `QTD_CONTRATADA`,
ADD COLUMN `QTD_PENDENTE` decimal(9,2) DEFAULT NULL AFTER `QTD_EXECUTADA`;

-- 13. ADICIONAR CAMPO CENTROCUSTOENTREGA NA TABELA FAT_PEDIDO
-- =====================================================
ALTER TABLE `FAT_PEDIDO` 
ADD COLUMN `COMPRADOR` varchar(45) DEFAULT NULL AFTER `VOLUME`,
ADD COLUMN `CENTROCUSTOENTREGA` int DEFAULT NULL AFTER `COMPRADOR`;
ADD COLUMN `PLACAVEICULO` varchar(15) DEFAULT NULL AFTER `CENTROCUSTOENTREGA`,
ADD COLUMN `VOLESPECIE` varchar(45) DEFAULT NULL AFTER `PLACAVEICULO`,
ADD COLUMN `VOLMARCA` varchar(45) DEFAULT NULL AFTER `VOLESPECIE`,
ADD COLUMN `VOLPESOLIQ` int DEFAULT NULL AFTER `VOLMARCA`,
ADD COLUMN `VOLPESOBRUTO` int DEFAULT NULL AFTER `VOLPESOLIQ`;

-- 14. ADICIONAR CAMPO VOLMARCA NA TABELA FAT_PEDIDO
-- =====================================================
ALTER TABLE `FAT_PEDIDO` 
ADD COLUMN `VOLMARCA` varchar(45) DEFAULT NULL AFTER `VOLPESOLIQ`;

-- 15. VERIFICAR SE O CAMPO PRODUTO JÁ EXISTE EM EST_NAT_OP_TRIBUTO
-- =====================================================
-- Se não existir, executar:
-- ALTER TABLE EST_NAT_OP_TRIBUTO ADD `PRODUTO` varchar(25) DEFAULT NULL AFTER CEST;

-- 16. ADICIONAR CAMPO MARCA NA TABELA EST_PRODUTO
-- =====================================================
ALTER TABLE `EST_PRODUTO` 
ADD COLUMN `MARCA` varchar(9) DEFAULT NULL AFTER `GRUPO`;

-- 17. ADICIONAR CAMPO VENDAPRESENCIAL NA TABELA EST_NOTA_FISCAL
-- =====================================================
ALTER TABLE `EST_NOTA_FISCAL` 
ADD COLUMN `VENDAPRESENCIAL` char(1) DEFAULT 'N' AFTER `GENERO`;

-- 18. ALTERAR TAMANHO DO CAMPO MARCA NA TABELA EST_MARCA
-- =====================================================
ALTER TABLE `EST_MARCA` 
MODIFY COLUMN `MARCA` varchar(9) NOT NULL;

-- admsis_concreta.EST_MARCA definição

CREATE TABLE `EST_MARCA` (
  `MARCA` varchar(5) NOT NULL,
  `DESCRICAO` varchar(30) NOT NULL,
  PRIMARY KEY (`MARCA`)
);

-- 19. ADICIONAR CAMPOS ADICIONAIS NA TABELA EST_NOTA_FISCAL_PRODUTO
-- =====================================================
ALTER TABLE `EST_NOTA_FISCAL_PRODUTO` 
ADD COLUMN `CSTIPI` varchar(2) DEFAULT NULL AFTER `ENQIPI`,
ADD COLUMN `BCIPI` decimal(11,2) DEFAULT 0.00 AFTER `CSTIPI`,
ADD COLUMN `VICMSSUBSTITUTO` decimal(11,2) DEFAULT NULL AFTER `BCIPI`,
ADD COLUMN `PCREDSN` decimal(7,4) DEFAULT 0.0000 AFTER `VICMSSUBSTITUTO`,
ADD COLUMN `VCREDICMSSN` decimal(11,2) DEFAULT 0.00 AFTER `PCREDSN`,
ADD COLUMN `USRFATURA` varchar(3) DEFAULT NULL AFTER `VCREDICMSSN`,
ADD COLUMN `CUSTO` decimal(11,4) DEFAULT NULL AFTER `USRFATURA`,
ADD COLUMN `DESPESAS` decimal(11,4) DEFAULT NULL AFTER `CUSTO`,
ADD COLUMN `LUCROBRUTO` decimal(11,4) DEFAULT NULL AFTER `DESPESAS`,
ADD COLUMN `MARGEMLIQUIDA` decimal(11,4) DEFAULT NULL AFTER `LUCROBRUTO`,
ADD COLUMN `MARKUP` decimal(11,4) DEFAULT NULL AFTER `MARGEMLIQUIDA`,
ADD COLUMN `FRETE` decimal(11,4) DEFAULT NULL AFTER `MARKUP`,
ADD COLUMN `DESCONTOGERAL` decimal(11,4) DEFAULT NULL AFTER `FRETE`,
ADD COLUMN `DESPACESSORIAS` decimal(11,4) DEFAULT NULL AFTER `DESCONTOGERAL`,
ADD COLUMN `CODIGONOTA` varchar(60) DEFAULT NULL AFTER `DESPACESSORIAS`;

-- 20. INSERIR REGISTROS DE CST IPI NA TABELA AMB_DDM
-- =====================================================
INSERT INTO `AMB_DDM` (ALIAS,NRCAMPO,CAMPO,TIPO,TAMANHO,DECIMAIS,FORMATO,REQUERIDO,PADRAO,LEGENDA,MASCARA,NOMEEXTERNO,ALTERACAO,DESCRICAO,`SQL`,MENSAGEM,MENU) VALUES
('FAT_MENU',959,'CSTIPI','00',0,0,NULL,'N','00- ENTRADA COM RECUPERAÇÃO DE CRÉDITO',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('FAT_MENU',960,'CSTIPI','01',0,0,NULL,'N','01 - ENTRADA TRIBUTADA COM ALÍQUOTA ZERO',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('FAT_MENU',961,'CSTIPI','02',0,0,NULL,'N','02 - ENTRADA ISENTA',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('FAT_MENU',962,'CSTIPI','03',0,0,NULL,'N','03 - ENTRADA NÃO TRIBUTADA',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('FAT_MENU',963,'CSTIPI','04',0,0,NULL,'N','04 - ENTRADA IMUNE',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('FAT_MENU',964,'CSTIPI','05',0,0,NULL,'N','05 - ENTRADA COM SUSPENSÃO',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('FAT_MENU',965,'CSTIPI','51',0,0,NULL,'N','51 - SAÍDA TRIBUTADA COM ALÍQUOTA ZERO',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('FAT_MENU',966,'CSTIPI','52',0,0,NULL,'N','52 - SAÍDA ISENTA',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('FAT_MENU',967,'CSTIPI','53',0,0,NULL,'N','53 - SAÍDA NÃO-TRIBUTADA',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('FAT_MENU',968,'CSTIPI','54',0,0,NULL,'N','54 - SAÍDA IMUNE',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('FAT_MENU',969,'CSTIPI','55',0,0,NULL,'N','55 - SAÍDA COM SUSPENSÃO',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('FAT_MENU',970,'CSTIPI','99',0,0,NULL,'N','99 - OUTRAS SAÍDAS',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('FAT_MENU',971,'CSTIPI','49',0,0,NULL,'N','49 - OUTRAS ENTRADAS',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('FAT_MENU',972,'CSTIPI','50',0,0,NULL,'N','50 - SAÍDA TRIBUTADA',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);


-- 21. ADICIONAR CAMPO USER_COLOR NA TABELA AMB_USUARIO
-- =====================================================
ALTER TABLE `AMB_USUARIO` 
ADD COLUMN `USER_COLOR` varchar(15) DEFAULT NULL AFTER `FIMTARDE`;

-- 22. ADICIONAR CAMPO EQUIPE_ID NA TABELA CAT_ATENDIMENTO

-- 22.1. TRANSFORMAR VALORES VAZIOS EM NULL PARA CONVERSÃO DO CAMPO PRAZOENTREGA
-- =====================================================
UPDATE `CAT_ATENDIMENTO`
SET `PRAZOENTREGA` = NULL
WHERE TRIM(`PRAZOENTREGA`) = '';

-- admsis_concreta.CAT_ATENDIMENTO definição

CREATE TABLE `CAT_ATENDIMENTO` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `NUMATENDIMENTO` int DEFAULT NULL,
  `CLIENTE` int NOT NULL,
  `CONTATO` varchar(30) DEFAULT NULL,
  `DATAABERATEND` timestamp NULL DEFAULT NULL,
  `DATAFECHATEND` timestamp NULL DEFAULT NULL,
  `USRABERTURA` smallint DEFAULT NULL,
  `PRIORIDADE` char(1) DEFAULT 'N',
  `PRAZOENTREGA` varchar(25) DEFAULT NULL,
  `DESCEQUIPAMENTO` varchar(60) DEFAULT NULL,
  `KMENTRADA` varchar(20) DEFAULT NULL,
  `OBS` text,
  `OBSSERVICO` text,
  `SOLUCAO` text,
  `VALORSERVICOS` decimal(12,2) DEFAULT NULL,
  `VALORPECAS` decimal(12,2) DEFAULT NULL,
  `VALORUTILIZADOPECAS` float DEFAULT NULL,
  `TOTALUTILIZADOPECAS` float DEFAULT NULL,
  `VALORVISITA` decimal(12,2) DEFAULT NULL,
  `VALORDESCONTO` decimal(12,2) DEFAULT NULL,
  `VALORTOTAL` decimal(12,2) DEFAULT NULL,
  `TIPOCOBRANCA` char(1) DEFAULT NULL,
  `CONDPGTO` varchar(100) DEFAULT NULL,
  `CONTA` smallint DEFAULT NULL,
  `GENERO` varchar(4) DEFAULT NULL,
  `CENTROCUSTO` int DEFAULT NULL,
  `CAT_SITUACAO_ID` int NOT NULL,
  `CAT_EQUIPAMENTO_ID` int DEFAULT NULL,
  `EQUIPE_ID` int DEFAULT NULL,
  `CAT_TIPO_ID` int NOT NULL,
  `PEDIDO_ID` int DEFAULT NULL,
  `CREATED_USER` int DEFAULT NULL,
  `UPDATED_USER` int DEFAULT NULL,
  `CREATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `UPDATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `fk_CAT_ATENDIMENTO_CAT_SITUACAO_idx` (`CAT_SITUACAO_ID`),
  KEY `fk_CAT_ATENDIMENTO_CAT_TIPO1_idx` (`CAT_TIPO_ID`),
  KEY `fk_CAT_ATENDIMENTO_CAT_EQUIPAMENTO1` (`CAT_EQUIPAMENTO_ID`),
  CONSTRAINT `fk_CAT_ATENDIMENTO_CAT_EQUIPAMENTO1` FOREIGN KEY (`CAT_EQUIPAMENTO_ID`) REFERENCES `CAT_EQUIPAMENTO` (`ID`),
  CONSTRAINT `fk_CAT_ATENDIMENTO_CAT_SITUACAO` FOREIGN KEY (`CAT_SITUACAO_ID`) REFERENCES `CAT_SITUACAO` (`ID`),
  CONSTRAINT `fk_CAT_ATENDIMENTO_CAT_TIPO1` FOREIGN KEY (`CAT_TIPO_ID`) REFERENCES `CAT_TIPO` (`ID`)
);

-- 22.2. ALTERAR O TIPO DO CAMPO PRAZOENTREGA PARA DATETIME
-- =====================================================
ALTER TABLE `CAT_ATENDIMENTO`
MODIFY COLUMN `PRAZOENTREGA` datetime DEFAULT NULL;

-- =====================================================

-- 23. REMOVER PADRÃO DO CAMPO DATAABERATEND NA TABELA CAT_ATENDIMENTO
-- =====================================================
ALTER TABLE `CAT_ATENDIMENTO` 
MODIFY COLUMN `DATAABERATEND` timestamp NOT NULL;

-- 24. ADICIONAR CAMPO DATANASCIMENTO NA TABELA FIN_CLIENTE
-- =====================================================
ALTER TABLE `FIN_CLIENTE` 
ADD COLUMN `DATANASCIMENTO` date DEFAULT NULL AFTER `MALADIRETA`;

-- 25. ALTERAR CAMPO NOMEREDUZIDO PARA VARCHAR(60) NA TABELA FIN_CLIENTE
-- =====================================================
ALTER TABLE `FIN_CLIENTE` 
MODIFY COLUMN `NOMEREDUZIDO` varchar(60) NOT NULL;

-- 26. ADICIONAR CAMPOS ADICIONAIS NA TABELA FIN_CLIENTE_ACOMP
-- =====================================================
ALTER TABLE `FIN_CLIENTE_ACOMP` 
ADD COLUMN `PEDIDO_ID` int DEFAULT NULL AFTER `PESSOA`,
ADD COLUMN `USERINSERT` int DEFAULT NULL AFTER `CUSTOKM`,
ADD COLUMN `DATEINSERT` timestamp DEFAULT CURRENT_TIMESTAMP AFTER `USERINSERT`,
ADD COLUMN `USERCHANGE` int DEFAULT NULL AFTER `DATEINSERT`,
ADD COLUMN `DATECHANGE` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP AFTER `USERCHANGE`,
ADD COLUMN `STATUS` char(1) DEFAULT 'A' AFTER `DATECHANGE`;

-- 27. ADICIONAR CAMPOS NA TABELA CAT_SERVICO
-- =====================================================
ALTER TABLE `CAT_SERVICO` 
ADD COLUMN `SITUACAO_TRIBUTARIA` int DEFAULT NULL AFTER `VALORUNITARIO`,
ADD COLUMN `TRIBUTA_MUNICIPIO_PRESTADOR` char(1) DEFAULT NULL COMMENT '0 quando a tributação ocorre no local da prestação do serviço 1 quando a tributação ocorre no município do prestador' AFTER `SITUACAO_TRIBUTARIA`;

-- admsis_concreta.CAT_SERVICO definição

CREATE TABLE `CAT_SERVICO` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `DESCRICAO` varchar(60) NOT NULL,
  `UNIDADE` varchar(3) NOT NULL,
  `QUANTIDADE` decimal(6,2) DEFAULT NULL,
  `VALORUNITARIO` decimal(8,2) NOT NULL,
  `STATUS` tinyint(1) NOT NULL DEFAULT '1' COMMENT '0 - Inativo, 1 - Ativo',
  `CREATED_USER` int DEFAULT NULL,
  `UPDATED_USER` int DEFAULT NULL,
  `CREATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `UPDATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
);
-- 28. CRIAR TABELA EST_NOTA_FISCAL_SERVICO_EVENTOS
-- =====================================================
CREATE TABLE `EST_NOTA_FISCAL_SERVICO_EVENTOS` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `ID_NFS` int NOT NULL,
  `CENTRO_CUSTO` varchar(11) NOT NULL,
  `SERIE` varchar(3) DEFAULT NULL,
  `NUMERO` int DEFAULT NULL,
  `TIPO_EVENTO` char(1) DEFAULT NULL COMMENT 'C - Cancelamento, E - Emissão, S - Solicitação de cancelamento (após o prazo), N - Consulta de NFS',
  `CODIGO_RETORNO` varchar(10) DEFAULT NULL,
  `XML_RETORNO` text,
  `CREATED_USER` int DEFAULT NULL,
  `CREATED_AT` timestamp DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
);

-- 29. CRIAR TABELA EST_SERVICOS_CODIGOS
-- =====================================================
CREATE TABLE `EST_SERVICOS_CODIGOS` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `CODIGO` varchar(10) NOT NULL,
  `SERVICO` text NOT NULL,
  `ALIQUOTA` decimal(5,2) NOT NULL,
  `RETENCAO` char(1) NOT NULL COMMENT '0 - Não, 1 - Sim',
  `RETENCAO_LEI_189_25` char(1) NOT NULL COMMENT '0 - Não, 1 - Sim',
  `OBRAS` char(1) NOT NULL COMMENT '0 - Não, 1 - Sim',
  `UF` varchar(2) NOT NULL,
  `COD_MUNICIPIO` varchar(10) NOT NULL,
  `MUNICIPIO` varchar(30) NOT NULL,
  `CREATED_USER` int DEFAULT NULL,
  `CREATED_AT` datetime DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_USER` int DEFAULT NULL,
  `UPDATED_AT` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
);

-- 30. CRIAR TABELA EST_NOTA_FISCAL_SERVICO
-- =====================================================
CREATE TABLE `EST_NOTA_FISCAL_SERVICO` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `IDENTIFICADOR_ARQUIVO` varchar(80) DEFAULT NULL UNIQUE,
  `NUMERO` int DEFAULT NULL,
  `SERIE` int DEFAULT NULL,
  `DATA_EMISSAO` date DEFAULT NULL,
  `HORA_EMISSAO` time DEFAULT NULL,
  `COD_VERIFICADOR_AUTENTICIDADE` varchar(16) DEFAULT NULL,
  `LINK_NFSE` varchar(500) DEFAULT NULL,
  `SITUACAO` int(1) DEFAULT NULL COMMENT '1-Emitida / 2-Cancelada',
  `RPS_NUMERO` varchar(9) DEFAULT NULL,
  `RPS_SERIE` varchar(2) DEFAULT NULL,
  `RPS_DATA_EMISSAO` date DEFAULT NULL,
  `RPS_HORA_EMISSAO` time DEFAULT NULL,
  `COD_EQUIPAMENTO_AUTOMATICO` varchar(100) DEFAULT NULL,
  `DATA_FATO_GERADOR` date DEFAULT NULL,
  `OBSERVACAO` varchar(1000) DEFAULT NULL,
  `VALOR_TOTAL` decimal(15,2) NOT NULL DEFAULT 0.00,
  `VALOR_DESCONTO` decimal(15,2) NOT NULL DEFAULT 0.00,
  `VALOR_IR` decimal(15,2) NOT NULL DEFAULT 0.00,
  `VALOR_INSS` decimal(15,2) NOT NULL DEFAULT 0.00,
  `VALOR_CONTRIBUICAO_SOCIAL` decimal(15,2) NOT NULL DEFAULT 0.00,
  `VALOR_RPS_RETENCAO` decimal(15,2) NOT NULL DEFAULT 0.00,
  `VALOR_PIS` decimal(15,2) NOT NULL DEFAULT 0.00,
  `VALOR_COFINS` decimal(15,2) NOT NULL DEFAULT 0.00,
  `PRESTADOR_CPFCNPJ` varchar(14) DEFAULT NULL,
  `PRESTADOR_CIDADE_CODIGO` int DEFAULT NULL,
  `TOMADOR_ID` int NOT NULL,
  `TOMADOR_CPFCNPJ` varchar(14) DEFAULT NULL,
  `TOMADOR_TIPO` char(1) DEFAULT NULL COMMENT 'F-Física / J-Jurídica / E-Estrangeiro',
  `TOMADOR_NOME_RAZAO_SOCIAL` varchar(100) DEFAULT NULL,
  `TOMADOR_NOME_FANTASIA` varchar(100) DEFAULT NULL,
  `TOMADOR_IE` varchar(16) DEFAULT NULL,
  `TOMADOR_EMAIL` varchar(100) DEFAULT NULL,
  `TOMADOR_ENDERECO_INFORMADO` char(1) DEFAULT NULL COMMENT '1-Sim / 0-Não',
  `TOMADOR_LOGRADOURO` varchar(70) DEFAULT NULL,
  `TOMADOR_NUMERO_RESIDENCIA` varchar(8) DEFAULT NULL,
  `TOMADOR_COMPLEMENTO` varchar(50) DEFAULT NULL,
  `TOMADOR_BAIRRO` varchar(30) DEFAULT NULL,
  `TOMADOR_CIDADE_CODIGO` varchar(100) DEFAULT NULL,
  `TOMADOR_CEP` varchar(8) DEFAULT NULL,
  `TOMADOR_PONTO_REFERENCIA` varchar(100) DEFAULT NULL,
  `TOMADOR_DDD_FONE_COMERCIAL` varchar(3) DEFAULT NULL,
  `TOMADOR_FONE_COMERCIAL` varchar(9) DEFAULT NULL,
  `TOMADOR_DDD_FONE_RESIDENCIAL` varchar(3) DEFAULT NULL,
  `TOMADOR_FONE_RESIDENCIAL` varchar(9) DEFAULT NULL,
  `TOMADOR_DDD_FAX` varchar(3) DEFAULT NULL,
  `TOMADOR_FONE_FAX` varchar(9) DEFAULT NULL,
  `TOMADOR_IDENTIFICADOR_ESTRANGEIRO` varchar(20) DEFAULT NULL,
  `TOMADOR_ESTADO_ESTRANGEIRO` varchar(100) DEFAULT NULL,
  `TOMADOR_PAIS_ESTRANGEIRO` varchar(100) DEFAULT NULL,
  `PRODUTOS_DESCRICAO` varchar(200) DEFAULT NULL COMMENT 'Tudo que se quer que saia na nota a respeito dos produtos',
  `PRODUTOS_VALOR_TOTAL` decimal(15,2) NOT NULL DEFAULT 0.00,
  `FORMA_PAGAMENTO_TIPO` int DEFAULT NULL COMMENT '1-À vista / 2-A prazo / 3-Na Apresentação / 4-Cartão de Débito / 5-Cartão de Crédito',
  `CREATED_USER` int NOT NULL,
  `CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_USER` int DEFAULT NULL,
  `UPDATED_AT` timestamp NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
);

-- 31. CRIAR TABELA EST_NOTA_FISCAL_SERVICO_ITEM
-- =====================================================
CREATE TABLE `EST_NOTA_FISCAL_SERVICO_ITEM` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `ID_NOTA_FISCAL_SERVICO` int NOT NULL,
  `ID_CAT_SERVICO` int NOT NULL,
  `TRIBUTA_MUNICIPIO_PRESTADOR` char(1) DEFAULT NULL COMMENT '1-Sim (tributação ocorre no município do prestador) / 0-Não (tributação ocorre no local da prestação do serviço)',
  `CODIGO_LOCAL_PRESTACAO_SERVICO` int DEFAULT NULL,
  `CODIGO_ITEM_LISTA_SERVICO` varchar(9) DEFAULT NULL,
  `DESCRITIVO` varchar(1000) DEFAULT NULL,
  `ALIQUOTA` decimal(5,2) NOT NULL DEFAULT 0.00,
  `SITUACAO_TRIBUTARIA` int DEFAULT NULL,
  `VALOR_TRIBUTAVEL` decimal(15,2) NOT NULL DEFAULT 0.00,
  `VALOR_DEDUCAO` decimal(15,2) NOT NULL DEFAULT 0.00,
  `VALOR_ISSRF` decimal(15,2) NOT NULL DEFAULT 0.00,
  `UNIDADE_CODIGO` int DEFAULT NULL,
  `UNIDADE_QUANTIDADE` decimal(15,2) DEFAULT NULL,
  `UNIDADE_VALOR_UNITARIO` decimal(15,2) NOT NULL DEFAULT 0.00,
  `CREATED_USER` int NOT NULL,
  `CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_USER` int DEFAULT NULL,
  `UPDATED_AT` timestamp NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `fk_EST_NOTA_FISCAL_SERVICO_ITEM_EST_NOTA_FISCAL_SERVICO1_idx` (`ID_NOTA_FISCAL_SERVICO`),
  KEY `fk_EST_NOTA_FISCAL_SERVICO_ITEM_CAT_SERVICO1_idx` (`ID_CAT_SERVICO`),
  CONSTRAINT `fk_EST_NOTA_FISCAL_SERVICO_ITEM_EST_NOTA_FISCAL_SERVICO1` FOREIGN KEY (`ID_NOTA_FISCAL_SERVICO`) REFERENCES `EST_NOTA_FISCAL_SERVICO` (`ID`),
  CONSTRAINT `fk_EST_NOTA_FISCAL_SERVICO_ITEM_CAT_SERVICO1` FOREIGN KEY (`ID_CAT_SERVICO`) REFERENCES `CAT_SERVICO` (`ID`)
);

-- 32. CRIAR TABELA CAT_AT_EQUIPE
-- =====================================================
CREATE TABLE `CAT_AT_EQUIPE` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `CAT_ATENDIMENTO_ID` int NOT NULL,
  `EQUIPE_EQUIPAMENTO_ID` int NOT NULL,
  `CAT_USUARIO_ID` int NOT NULL,
  `CREATED_USER` int DEFAULT NULL,
  `UPDATED_USER` int DEFAULT NULL,
  `CREATED_AT` timestamp DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb3;

-- 33. ADICIONAR CAMPOS ADICIONAIS NA TABELA FAT_PEDIDO
-- =====================================================
ALTER TABLE `FAT_PEDIDO` 
ADD COLUMN `ODESFERICO` varchar(10) DEFAULT NULL AFTER `IDAGRUPAMENTO`,
ADD COLUMN `OEESFERICO` varchar(10) DEFAULT NULL AFTER `ODESFERICO`,
ADD COLUMN `ODCILINDRICO` varchar(10) DEFAULT NULL AFTER `OEESFERICO`,
ADD COLUMN `OECILINDRICO` varchar(10) DEFAULT NULL AFTER `ODCILINDRICO`,
ADD COLUMN `ODEIXO` varchar(10) DEFAULT NULL AFTER `OECILINDRICO`,
ADD COLUMN `OEEIXO` varchar(10) DEFAULT NULL AFTER `ODEIXO`,
ADD COLUMN `ODAD` varchar(10) DEFAULT NULL AFTER `OEEIXO`,
ADD COLUMN `OEAD` varchar(10) DEFAULT NULL AFTER `ODAD`,
ADD COLUMN `MEDICO` varchar(60) DEFAULT NULL AFTER `OEAD`,
ADD COLUMN `OPORTUNIDADE` text DEFAULT NULL AFTER `MEDICO`,
ADD COLUMN `APRESENTACAO` text DEFAULT NULL AFTER `OPORTUNIDADE`,
ADD COLUMN `OBJETIVO` text DEFAULT NULL AFTER `APRESENTACAO`,
ADD COLUMN `GARANTIA` text DEFAULT NULL AFTER `OBJETIVO`,
ADD COLUMN `IMPOSTOS` text DEFAULT NULL AFTER `GARANTIA`,
ADD COLUMN `VALIDADE` text DEFAULT NULL AFTER `IMPOSTOS`,
ADD COLUMN `ACEITE` text DEFAULT NULL AFTER `VALIDADE`;

-- 34. ADICIONAR CAMPO PRECCREDITOSIMPLES NA TABELA EST_NAT_OP
-- =====================================================
ALTER TABLE `EST_NAT_OP` 
ADD COLUMN `PRECCREDITOSIMPLES` decimal(5,2) DEFAULT NULL AFTER `TRIBSIMPLES`;

-- 35. ADICIONAR CAMPO ANP NA TABELA EST_PRODUTO
-- =====================================================
ALTER TABLE `EST_PRODUTO` 
ADD COLUMN `ANP` text DEFAULT NULL AFTER `PERCCALCULO`;

-- 36. ALTERAR CAMPO GENERO PARA VARCHAR(6) NA TABELA FIN_LANCAMENTO
-- =====================================================
ALTER TABLE `FIN_LANCAMENTO` 
MODIFY COLUMN `GENERO` varchar(6) NOT NULL;

-- 37. ADICIONAR CAMPO CASASDECIMAIS NA TABELA FAT_PARAMETRO
-- =====================================================
ALTER TABLE `FAT_PARAMETRO` 
ADD COLUMN `TIPODESCONTO` char(1) DEFAULT 'T' AFTER `LANCPEDBAIXADO`,
ADD COLUMN `CASASDECIMAIS` int DEFAULT 4 NOT NULL AFTER `TIPODESCONTO`;


-- 38. CRIAR TABELA AMB_RESPONSAVEL_TECNICO
-- =====================================================

CREATE TABLE `AMB_RESPONSAVEL_TECNICO` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(100) NOT NULL COMMENT 'NOME COMPLETO DO RESPONSÁVEL TÉCNICO',
  `CPF` VARCHAR(14) DEFAULT NULL COMMENT 'CPF DO RESPONSÁVEL TÉCNICO',
  `CREA` VARCHAR(20) DEFAULT NULL COMMENT 'NÚMERO DO CREA',
  `TELEFONE` VARCHAR(20) DEFAULT NULL COMMENT 'TELEFONE DE CONTATO',
  `EMAIL` VARCHAR(100) DEFAULT NULL COMMENT 'E-MAIL DE CONTATO',
  `CEP` VARCHAR(10) DEFAULT NULL COMMENT 'CEP',
  `RUA` VARCHAR(200) DEFAULT NULL COMMENT 'RUA',
  `NUMERO` VARCHAR(10) DEFAULT NULL COMMENT 'NÚMERO',
  `COMPLEMENTO` VARCHAR(100) DEFAULT NULL COMMENT 'COMPLEMENTO',
  `ESTADO` VARCHAR(2) DEFAULT NULL COMMENT 'ESTADO (UF)',
  `CIDADE` VARCHAR(50) DEFAULT NULL COMMENT 'CIDADE',
  `SITUACAO` CHAR(1) NOT NULL DEFAULT 'A' COMMENT 'SITUAÇÃO: A=ATIVO, I=INATIVO',
  `CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'DATA DE CADASTRO',
  `UPDATED_AT` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT 'DATA DA ÚLTIMA ALTERAÇÃO',
  `CREATED_BY` INT(11) DEFAULT NULL COMMENT 'USUÁRIO QUE CADASTROU',
  `UPDATED_BY` INT(11) DEFAULT NULL COMMENT 'USUÁRIO QUE ALTEROU',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_CPF` (`CPF`),
  UNIQUE KEY `UK_CREA` (`CREA`),
  KEY `IDX_NOME` (`NOME`),
  KEY `IDX_SITUACAO` (`SITUACAO`)
);

-- 39. INCLUIR DIREITO NO AMB_USUARIO_AUTORIZA
-- =====================================================
INSERT INTO `AMB_USUARIO_AUTORIZA` (`usuario`, `programa`, `direitos`) VALUES (999, 'AMBRESPONSAVELTECNICO', 'IAECSR');


-- 40. ALTERAR TABELA FAT_PEDIDO PARA ADICIONAR O CAMPO RESP_TECNICO
-- =====================================================
ALTER TABLE `FAT_PEDIDO` 
ADD COLUMN `RESP_TECNICO` int NULL AFTER `OBRA_ID`;


-- 41. ALTERAR TABELA EST_NOTA_FISCAL PARA ADICIONAR OS CAMPOS CODANTT E UF
-- =====================================================
ALTER TABLE `EST_NOTA_FISCAL` 
ADD COLUMN `CODANTT` VARCHAR(20) AFTER `PLACAVEICULO`,
ADD COLUMN `UF` VARCHAR(2) AFTER `CODANTT`;

-- 42. ALTERAR TABELA FAT_PEDIDO PARA ADICIONAR O CAMPO ENDERECOENTREGA
-- =====================================================
ALTER TABLE `FAT_PEDIDO` 
ADD COLUMN `ENDERECOENTREGA` int NULL AFTER `MODFRETE`;

-- 43. ALTERAR TABELA FAT_PARAMETRO PARA ADICIONAR O CAMPO CONTROLEVENDEDOR
-- =====================================================
ALTER TABLE `FAT_PARAMETRO` 
ADD COLUMN `CONTROLEVENDEDOR` int(1) DEFAULT '0' COMMENT '1=Controla vendedor, 0=Não controla';

-- 44. ALTERAR TABELA FIN_CLIENTE PARA ADICIONAR O CAMPO EMAILNFE
ALTER TABLE FIN_CLIENTE 
MODIFY COLUMN EMAILNFE TEXT NULL;
-- =====================================================
-- FIM DAS ALTERAÇÕES DOS ARQUIVOS DE ATUALIZAÇÃO
-- =====================================================

