-- =====================================================
-- ALTERAÇÕES NECESSÁRIAS PARA ATUALIZAR BANCO ADM v4.5
-- =====================================================
-- Data: $(date)
-- Versão: 4.5
-- Descrição: Script de alterações para bancos existentes
-- =====================================================

-- 1. ADICIONAR CAMPO BLOQUEADO NA TABELA FAT_COND_PGTO
-- =====================================================
ALTER TABLE `FAT_COND_PGTO` 
ADD COLUMN `SITUACAOLCTO` char(1) NOT NULL DEFAULT 'A' AFTER `NUMPARCELAS`,
ADD COLUMN `BLOQUEADO` char(1) NOT NULL DEFAULT 'A' AFTER `SITUACAOLCTO`;

-- 2. ALTERAR TABELA EST_GRUPO PARA AUTO_INCREMENT E ADICIONAR CAMPOS DE AUDITORIA
-- =====================================================
-- Primeiro, criar tabela temporária com nova estrutura
CREATE TABLE `EST_GRUPO_NEW` (  
  `ID` int NOT NULL AUTO_INCREMENT,
  `GRUPO` varchar(15) NOT NULL DEFAULT '',
  `DESCRICAO` varchar(40) NOT NULL,
  `TIPO` char(1) NOT NULL,
  `NIVEL` smallint NOT NULL,
  `COMISSAOVENDAS` decimal(5,2) DEFAULT NULL,
  `USERINSERT` int DEFAULT NULL,
  `DATEINSERT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `USERCHANGE` int DEFAULT NULL,
  `DATECHANGE` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

-- Copiar dados existentes (ajustar conforme necessário)
INSERT INTO `EST_GRUPO_NEW` (`GRUPO`,`DESCRICAO`, `TIPO`, `NIVEL`)
SELECT `GRUPO`, `DESCRICAO`, `TIPO`, `NIVEL` FROM `EST_GRUPO`;

-- Remover tabela antiga e renomear nova
DROP TABLE `EST_GRUPO`;
RENAME TABLE `EST_GRUPO_NEW` TO `EST_GRUPO`;

-- 3. ADICIONAR TABELA EST_PRODUTO_EQUIVALENCIA
-- =====================================================
CREATE TABLE `EST_PRODUTO_EQUIVALENCIA` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `IDPRODUTO` int NOT NULL,
  `CODEQUIVALENTE` varchar(25) DEFAULT NULL,
  `CONTA` int DEFAULT NULL,
  `NFULTIMACOMPRA` int DEFAULT NULL,
  `DATAULTIMACOMPRA` date DEFAULT NULL,
  `QUANTULTIMACOMPRA` int DEFAULT NULL,
  `USERINSERT` int DEFAULT NULL,
  `DATEINSERT` timestamp NULL DEFAULT NULL,
  `USERCHANGE` int DEFAULT NULL,
  `DATECHANGE` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `CODFAB` (`IDPRODUTO`,`CODEQUIVALENTE`)
) ENGINE=InnoDB AUTO_INCREMENT=36639 DEFAULT CHARSET=utf8mb4;



-- 4. ADICIONAR CAMPO OBRA_ID NA TABELA FAT_PEDIDO
-- =====================================================
ALTER TABLE `FAT_PEDIDO` 
ADD COLUMN `OBRA_ID` int DEFAULT NULL AFTER `OS`;

-- 5. ADICIONAR CAMPO OBSSERVICO E ALTERAR UNIDADE NA TABELA FAT_PEDIDO_SERVICO
-- =====================================================
-- Adicionar campo OBSSERVICO
ALTER TABLE `FAT_PEDIDO_SERVICO`

ADD COLUMN `OBSSERVICO` text AFTER `DESCSERVICO`;

--IVEMAR - MAXIFARMA
DROP TABLE `FAT_PEDIDO_SERVICO`;

CREATE TABLE `FAT_PEDIDO_SERVICO` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `FAT_PEDIDO_ID` int(11) NOT NULL,
  `ID_USER` int(11) NOT NULL,
  `DATA` date DEFAULT NULL,
  `HORAINI` time DEFAULT NULL,
  `HORAFIM` time DEFAULT NULL,
  `HORATOTAL` time DEFAULT NULL,
  `CUSTOUSER` decimal(9,2) DEFAULT NULL,
  `DESCSERVICO` mediumtext DEFAULT NULL,
  `OBSSERVICO` mediumtext DEFAULT NULL,
  `UNIDADE` varchar(10) DEFAULT NULL,
  `QUANTIDADE` decimal(9,2) DEFAULT NULL,
  `VALUNITARIO` decimal(9,2) DEFAULT NULL,
  `TOTALSERVICO` decimal(9,2) DEFAULT NULL,
  `CAT_SERVICOS_ID` int(11) NOT NULL,
  `CREATED_USER` int(11) DEFAULT NULL,
  `UPDATED_USER` int(11) DEFAULT NULL,
  `CREATED_AT` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `UPDATED_AT` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`ID`),
  KEY `fk_FAT_PEDIDO_SERVICO_FAT_PEDIDO1_idx` (`FAT_PEDIDO_ID`),
  KEY `fk_FAT_PEDIDO_SERVICO_CAT_SERVICOS1_idx` (`CAT_SERVICOS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Adicionar as constraints separadamente para evitar erro de FK mal formada
ALTER TABLE `FAT_PEDIDO_SERVICO`
  ADD CONSTRAINT `fk_FAT_PEDIDO_SERVICO_CAT_SERVICOS1`
    FOREIGN KEY (`CAT_SERVICOS_ID`) REFERENCES `CAT_SERVICO` (`ID`)
    ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE `FAT_PEDIDO_SERVICO`
  ADD CONSTRAINT `fk_FAT_PEDIDO_SERVICO_FAT_PEDIDO1`
    FOREIGN KEY (`FAT_PEDIDO_ID`) REFERENCES `FAT_PEDIDO` (`ID`)
    ON DELETE RESTRICT ON UPDATE CASCADE;


-- Alterar campo UNIDADE para suportar mais caracteres e UTF-8 completo
ALTER TABLE `FAT_PEDIDO_SERVICO` 
MODIFY COLUMN `UNIDADE` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL;

-- Alterar a tabela para usar UTF-8 completo
ALTER TABLE `FAT_PEDIDO_SERVICO` 
CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- 6. CRIAR TABELA FIN_CLIENTE_OBRA
-- =====================================================
CREATE TABLE `FIN_CLIENTE_OBRA` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `CNO` varchar(20) DEFAULT '0',
  `PROJETO` varchar(90) DEFAULT '0',
  `RESPONSAVEL_TECNICO` int DEFAULT '0',
  `CREA` varchar(20) DEFAULT NULL,
  `ART` varchar(20) DEFAULT NULL,
  `CLIENTE` int NOT NULL,
  `STATUS` char(1) NOT NULL DEFAULT 'A' COMMENT 'A-Ativo, I-Inativo',
  `USERINSERT` int DEFAULT NULL,
  `DATEINSERT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `USERCHANGE` int DEFAULT NULL,
  `DATECHANGE` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb3;

-- 7. CRIAR TABELA FIN_CLIENTE_ENDERECO
-- =====================================================
CREATE TABLE `FIN_CLIENTE_ENDERECO` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `CLIENTE` int NOT NULL,
  `DESCRICAO` varchar(35) NOT NULL,
  `TIPOEND` varchar(15) DEFAULT 'RUA',
  `TITULOEND` varchar(15) DEFAULT NULL,
  `ENDERECO` varchar(60) DEFAULT 'SEM ENDERECO',
  `NUMERO` varchar(7) DEFAULT 'S/N',
  `COMPLEMENTO` varchar(15) DEFAULT NULL,
  `BAIRRO` varchar(20) DEFAULT NULL,
  `CIDADE` varchar(40) DEFAULT 'SEM CIDADE',
  `UF` varchar(2) DEFAULT 'PR',
  `CEP` int DEFAULT NULL,
  `HORARIO` time DEFAULT NULL,
  `FONEAREA` varchar(4) DEFAULT NULL,
  `FONE` varchar(9) DEFAULT NULL,
  `FONERAMAL` varchar(4) DEFAULT NULL,
  `FONECONTATO` varchar(15) DEFAULT NULL,
  `ENDENTREGAPADRAO` char(1) DEFAULT 'N',
  `ENDRETIRADAPADRAO` char(1) DEFAULT 'N',
  `PAIS` varchar(3) DEFAULT NULL,
  `STATUS` char(1) DEFAULT 'A',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb3;

-- 8. CRIAR TABELA AMB_LOG
-- =====================================================
CREATE TABLE `AMB_LOG` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `ID_TABLE` int NOT NULL,
  `OPERACAO` varchar(10) COLLATE utf8mb3_bin DEFAULT NULL,
  `TABELA` varchar(20) COLLATE utf8mb3_bin DEFAULT NULL,
  `SQLSAVE` text COLLATE utf8mb3_bin,
  `USERINSERT` int DEFAULT NULL,
  `DATEINSERT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_bin;

-- admsis_modena.AMB_LOG_EMAIL definição

CREATE TABLE `AMB_LOG_EMAIL` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `NUMERO_NOTA` varchar(20) DEFAULT NULL,
  `ID_NOTA` int DEFAULT NULL,
  `USUARIO` varchar(100) DEFAULT NULL,
  `ERRO` text,
  `DATA_HORA` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
);


-- 9. CRIAR TABELA AMB_EQUIPE
-- =====================================================
CREATE TABLE `AMB_EQUIPE` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `DESCRICAO` varchar(100) NOT NULL,
  `COR_EQUIPE` varchar(50) NOT NULL COMMENT 'COR DE IDENTIFICAÇÃO DA EQUIPE',
  `CREATED_USER` int NOT NULL COMMENT 'USUÁRIO QUE CRIOU O REGISTRO',
  `UPDATED_USER` int DEFAULT NULL COMMENT 'USUÁRIO QUE ATUALIZOU O REGISTRO',
  `CREATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'DATA DE CRIAÇÃO',
  `UPDATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'DATA DE ATUALIZAÇÃO',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_AMB_EQUIPE_DESCRICAO` (`DESCRICAO`)
);

-- 10. CRIAR TABELA CAT_AT_EQUIPE_USUARIO
-- =====================================================
CREATE TABLE `CAT_AT_EQUIPE_USUARIO` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `ID_EQUIPE` int NOT NULL,
  `ID_USUARIO` int NOT NULL,
  `CAT_ATENDIMENTO_ID` int NOT NULL,
  `CREATED_USER` int NOT NULL COMMENT 'USUÁRIO QUE CRIOU O REGISTRO',
  `UPDATED_USER` int DEFAULT NULL COMMENT 'USUÁRIO QUE ATUALIZOU O REGISTRO',
  `CREATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'DATA DE CRIAÇÃO',
  `UPDATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'DATA DE ATUALIZAÇÃO',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_AT_EQUIPE_USUARIO_ATENDIMENTO` (`ID_EQUIPE`,`ID_USUARIO`,`CAT_ATENDIMENTO_ID`),
  KEY `CAT_ATENDIMENTO_ID` (`CAT_ATENDIMENTO_ID`),
  CONSTRAINT `CAT_AT_EQUIPE_USUARIO_ibfk_1` FOREIGN KEY (`ID_EQUIPE`) REFERENCES `AMB_EQUIPE` (`ID`) ON DELETE CASCADE,
  CONSTRAINT `CAT_AT_EQUIPE_USUARIO_ibfk_2` FOREIGN KEY (`CAT_ATENDIMENTO_ID`) REFERENCES `CAT_ATENDIMENTO` (`ID`) ON DELETE CASCADE
);

-- admsis_concreta.CAT_AT_SERVICOS definição

CREATE TABLE `CAT_AT_SERVICOS` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `ID_USER` int NOT NULL,
  `DATA` date DEFAULT NULL,
  `HORAINI` time DEFAULT NULL,
  `HORAFIM` time DEFAULT NULL,
  `HORATOTAL` time DEFAULT NULL,
  `CUSTOUSER` decimal(9,2) DEFAULT NULL,
  `DESCSERVICO` text,
  `UNIDADE` varchar(3) DEFAULT NULL,
  `QUANTIDADE` decimal(9,2) DEFAULT NULL,
  `QUANTIDADE_EXECUTADA` decimal(9,2) DEFAULT NULL,
  `VALUNITARIO` decimal(9,2) DEFAULT NULL,
  `TOTALSERVICO` decimal(9,2) DEFAULT NULL,
  `CAT_ATENDIMENTO_ID` int NOT NULL,
  `CAT_SERVICOS_ID` int NOT NULL,
  `CREATED_USER` int DEFAULT NULL,
  `UPDATED_USER` int DEFAULT NULL,
  `CREATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `UPDATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `fk_CAT_AT_SERVICOS_CAT_ATENDIMENTO1_idx` (`CAT_ATENDIMENTO_ID`),
  KEY `fk_CAT_AT_SERVICOS_CAT_SERVICOS1_idx` (`CAT_SERVICOS_ID`),
  CONSTRAINT `fk_CAT_AT_SERVICOS_CAT_ATENDIMENTO1` FOREIGN KEY (`CAT_ATENDIMENTO_ID`) REFERENCES `CAT_ATENDIMENTO` (`ID`),
  CONSTRAINT `fk_CAT_AT_SERVICOS_CAT_SERVICOS1` FOREIGN KEY (`CAT_SERVICOS_ID`) REFERENCES `CAT_SERVICO` (`ID`)
);

-- 11. ADICIONAR CAMPOS ADICIONAIS NA TABELA CAT_AT_SERVICOS
-- =====================================================
ALTER TABLE `CAT_AT_SERVICOS` 
ADD COLUMN `QUANTIDADE_EXECUTADA` decimal(9,2) DEFAULT NULL AFTER `QUANTIDADE`;

-- 13. ADICIONAR CAMPO CENTROCUSTOENTREGA NA TABELA FAT_PEDIDO
-- =====================================================
ALTER TABLE `FAT_PEDIDO` 
ADD COLUMN `COMPRADOR` varchar(45) DEFAULT NULL AFTER `VOLUME`,
ADD COLUMN `CENTROCUSTOENTREGA` int DEFAULT NULL AFTER `COMPRADOR`,
ADD COLUMN `PLACAVEICULO` varchar(15) DEFAULT NULL AFTER `CENTROCUSTOENTREGA`,
ADD COLUMN `VOLESPECIE` varchar(45) DEFAULT NULL AFTER `PLACAVEICULO`,
ADD COLUMN `VOLMARCA` varchar(45) DEFAULT NULL AFTER `VOLESPECIE`,
ADD COLUMN `VOLPESOLIQ` int DEFAULT NULL AFTER `VOLMARCA`,
ADD COLUMN `VOLPESOBRUTO` int DEFAULT NULL AFTER `VOLPESOLIQ`;

-- 14. ADICIONAR CAMPO VOLMARCA NA TABELA FAT_PEDIDO
-- =====================================================
ALTER TABLE `FAT_PEDIDO` 
ADD COLUMN `VOLMARCA` varchar(45) DEFAULT NULL AFTER `VOLPESOLIQ`;

-- 15. VERIFICAR SE O CAMPO PRODUTO JÁ EXISTE EM EST_NAT_OP_TRIBUTO
-- =====================================================
-- Se não existir, executar:
-- ALTER TABLE EST_NAT_OP_TRIBUTO ADD `PRODUTO` varchar(25) DEFAULT NULL AFTER CEST;

-- 16. ADICIONAR CAMPO MARCA NA TABELA EST_PRODUTO
-- =====================================================
ALTER TABLE `EST_PRODUTO` 
ADD COLUMN `MARCA` varchar(9) DEFAULT NULL AFTER `GRUPO`;

-- 17. ADICIONAR CAMPO VENDAPRESENCIAL NA TABELA EST_NOTA_FISCAL
-- =====================================================
ALTER TABLE `EST_NOTA_FISCAL` 
ADD COLUMN `VENDAPRESENCIAL` char(1) DEFAULT 'N' AFTER `GENERO`;

-- 18. ALTERAR TAMANHO DO CAMPO MARCA NA TABELA EST_MARCA
-- =====================================================
ALTER TABLE `EST_MARCA` 
MODIFY COLUMN `MARCA` varchar(9) NOT NULL;

-- admsis_concreta.EST_MARCA definição

CREATE TABLE `EST_MARCA` (
  `MARCA` varchar(5) NOT NULL,
  `DESCRICAO` varchar(30) NOT NULL,
  PRIMARY KEY (`MARCA`)
);

-- 19. ADICIONAR CAMPOS ADICIONAIS NA TABELA EST_NOTA_FISCAL_PRODUTO
-- =====================================================
ALTER TABLE `EST_NOTA_FISCAL_PRODUTO` 
ADD COLUMN `CSTIPI` varchar(2) DEFAULT NULL AFTER `ENQIPI`,
ADD COLUMN `BCIPI` decimal(11,2) DEFAULT 0.00 AFTER `CSTIPI`,
ADD COLUMN `VICMSSUBSTITUTO` decimal(11,2) DEFAULT NULL AFTER `BCIPI`,
ADD COLUMN `PCREDSN` decimal(7,4) DEFAULT 0.0000 AFTER `VICMSSUBSTITUTO`,
ADD COLUMN `VCREDICMSSN` decimal(11,2) DEFAULT 0.00 AFTER `PCREDSN`,
ADD COLUMN `USRFATURA` varchar(3) DEFAULT NULL AFTER `VCREDICMSSN`,
ADD COLUMN `CUSTO` decimal(11,4) DEFAULT NULL AFTER `USRFATURA`,
ADD COLUMN `DESPESAS` decimal(11,4) DEFAULT NULL AFTER `CUSTO`,
ADD COLUMN `LUCROBRUTO` decimal(11,4) DEFAULT NULL AFTER `DESPESAS`,
ADD COLUMN `MARGEMLIQUIDA` decimal(11,4) DEFAULT NULL AFTER `LUCROBRUTO`,
ADD COLUMN `MARKUP` decimal(11,4) DEFAULT NULL AFTER `MARGEMLIQUIDA`,
ADD COLUMN `FRETE` decimal(11,4) DEFAULT NULL AFTER `MARKUP`,
ADD COLUMN `DESCONTOGERAL` decimal(11,4) DEFAULT NULL AFTER `FRETE`,
ADD COLUMN `DESPACESSORIAS` decimal(11,4) DEFAULT NULL AFTER `DESCONTOGERAL`,
ADD COLUMN `CODIGONOTA` varchar(60) DEFAULT NULL AFTER `DESPACESSORIAS`;

-- 20. INSERIR REGISTROS DE CST IPI NA TABELA AMB_DDM
-- =====================================================
INSERT INTO `AMB_DDM` (ALIAS,NRCAMPO,CAMPO,TIPO,TAMANHO,DECIMAIS,FORMATO,REQUERIDO,PADRAO,LEGENDA,MASCARA,NOMEEXTERNO,ALTERACAO,DESCRICAO,`SQL`,MENSAGEM,MENU) VALUES
('FAT_MENU',959,'CSTIPI','00',0,0,NULL,'N','00- ENTRADA COM RECUPERAÇÃO DE CRÉDITO',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('FAT_MENU',960,'CSTIPI','01',0,0,NULL,'N','01 - ENTRADA TRIBUTADA COM ALÍQUOTA ZERO',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('FAT_MENU',961,'CSTIPI','02',0,0,NULL,'N','02 - ENTRADA ISENTA',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('FAT_MENU',962,'CSTIPI','03',0,0,NULL,'N','03 - ENTRADA NÃO TRIBUTADA',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('FAT_MENU',963,'CSTIPI','04',0,0,NULL,'N','04 - ENTRADA IMUNE',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('FAT_MENU',964,'CSTIPI','05',0,0,NULL,'N','05 - ENTRADA COM SUSPENSÃO',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('FAT_MENU',965,'CSTIPI','51',0,0,NULL,'N','51 - SAÍDA TRIBUTADA COM ALÍQUOTA ZERO',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('FAT_MENU',966,'CSTIPI','52',0,0,NULL,'N','52 - SAÍDA ISENTA',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('FAT_MENU',967,'CSTIPI','53',0,0,NULL,'N','53 - SAÍDA NÃO-TRIBUTADA',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('FAT_MENU',968,'CSTIPI','54',0,0,NULL,'N','54 - SAÍDA IMUNE',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('FAT_MENU',969,'CSTIPI','55',0,0,NULL,'N','55 - SAÍDA COM SUSPENSÃO',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('FAT_MENU',970,'CSTIPI','99',0,0,NULL,'N','99 - OUTRAS SAÍDAS',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('FAT_MENU',971,'CSTIPI','49',0,0,NULL,'N','49 - OUTRAS ENTRADAS',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('FAT_MENU',972,'CSTIPI','50',0,0,NULL,'N','50 - SAÍDA TRIBUTADA',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);


-- 21. ADICIONAR CAMPO USER_COLOR NA TABELA AMB_USUARIO
-- =====================================================
ALTER TABLE `AMB_USUARIO` 
ADD COLUMN `USER_COLOR` varchar(15) DEFAULT NULL AFTER `FIMTARDE`;

-- 22. ADICIONAR CAMPO EQUIPE_ID NA TABELA CAT_ATENDIMENTO

-- 22.1. TRANSFORMAR VALORES VAZIOS EM NULL PARA CONVERSÃO DO CAMPO PRAZOENTREGA
-- =====================================================
UPDATE `CAT_ATENDIMENTO`
SET `PRAZOENTREGA` = NULL
WHERE TRIM(`PRAZOENTREGA`) = '';

-- admsis_concreta.CAT_ATENDIMENTO definição

CREATE TABLE `CAT_ATENDIMENTO` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `NUMATENDIMENTO` int DEFAULT NULL,
  `CLIENTE` int NOT NULL,
  `CONTATO` varchar(30) DEFAULT NULL,
  `DATAABERATEND` timestamp NULL DEFAULT NULL,
  `DATAFECHATEND` timestamp NULL DEFAULT NULL,
  `USRABERTURA` smallint DEFAULT NULL,
  `PRIORIDADE` char(1) DEFAULT 'N',
  `PRAZOENTREGA` varchar(25) DEFAULT NULL,
  `DESCEQUIPAMENTO` varchar(60) DEFAULT NULL,
  `KMENTRADA` varchar(20) DEFAULT NULL,
  `OBS` text,
  `OBSSERVICO` text,
  `SOLUCAO` text,
  `VALORSERVICOS` decimal(12,2) DEFAULT NULL,
  `VALORPECAS` decimal(12,2) DEFAULT NULL,
  `VALORUTILIZADOPECAS` float DEFAULT NULL,
  `TOTALUTILIZADOPECAS` float DEFAULT NULL,
  `VALORVISITA` decimal(12,2) DEFAULT NULL,
  `VALORDESCONTO` decimal(12,2) DEFAULT NULL,
  `VALORTOTAL` decimal(12,2) DEFAULT NULL,
  `TIPOCOBRANCA` char(1) DEFAULT NULL,
  `CONDPGTO` varchar(100) DEFAULT NULL,
  `CONTA` smallint DEFAULT NULL,
  `GENERO` varchar(4) DEFAULT NULL,
  `CENTROCUSTO` int DEFAULT NULL,
  `CAT_SITUACAO_ID` int NOT NULL,
  `CAT_EQUIPAMENTO_ID` int DEFAULT NULL,
  `EQUIPE_ID` int DEFAULT NULL,
  `CAT_TIPO_ID` int NOT NULL,
  `PEDIDO_ID` int DEFAULT NULL,
  `CREATED_USER` int DEFAULT NULL,
  `UPDATED_USER` int DEFAULT NULL,
  `CREATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `UPDATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `fk_CAT_ATENDIMENTO_CAT_SITUACAO_idx` (`CAT_SITUACAO_ID`),
  KEY `fk_CAT_ATENDIMENTO_CAT_TIPO1_idx` (`CAT_TIPO_ID`),
  KEY `fk_CAT_ATENDIMENTO_CAT_EQUIPAMENTO1` (`CAT_EQUIPAMENTO_ID`),
  CONSTRAINT `fk_CAT_ATENDIMENTO_CAT_EQUIPAMENTO1` FOREIGN KEY (`CAT_EQUIPAMENTO_ID`) REFERENCES `CAT_EQUIPAMENTO` (`ID`),
  CONSTRAINT `fk_CAT_ATENDIMENTO_CAT_SITUACAO` FOREIGN KEY (`CAT_SITUACAO_ID`) REFERENCES `CAT_SITUACAO` (`ID`),
  CONSTRAINT `fk_CAT_ATENDIMENTO_CAT_TIPO1` FOREIGN KEY (`CAT_TIPO_ID`) REFERENCES `CAT_TIPO` (`ID`)
);

-- 22.2. ALTERAR O TIPO DO CAMPO PRAZOENTREGA PARA DATETIME
-- =====================================================
ALTER TABLE `CAT_ATENDIMENTO`
MODIFY COLUMN `PRAZOENTREGA` datetime DEFAULT NULL;

-- =====================================================

-- 23. REMOVER PADRÃO DO CAMPO DATAABERATEND NA TABELA CAT_ATENDIMENTO
-- =====================================================
ALTER TABLE `CAT_ATENDIMENTO` 
MODIFY COLUMN `DATAABERATEND` timestamp NOT NULL;

-- 24. ADICIONAR CAMPO DATANASCIMENTO NA TABELA FIN_CLIENTE
-- =====================================================
ALTER TABLE `FIN_CLIENTE` 
ADD COLUMN `DATANASCIMENTO` date DEFAULT NULL AFTER `MALADIRETA`;

-- 25. ALTERAR CAMPO NOMEREDUZIDO PARA VARCHAR(60) NA TABELA FIN_CLIENTE
-- =====================================================
ALTER TABLE `FIN_CLIENTE` 
MODIFY COLUMN `NOMEREDUZIDO` varchar(60) NOT NULL;

-- 26. ADICIONAR CAMPOS ADICIONAIS NA TABELA FIN_CLIENTE_ACOMP
-- =====================================================
ALTER TABLE `FIN_CLIENTE_ACOMP` 
ADD COLUMN `PEDIDO_ID` int DEFAULT NULL AFTER `PESSOA`,
ADD COLUMN `USERINSERT` int DEFAULT NULL AFTER `CUSTOKM`,
ADD COLUMN `DATEINSERT` timestamp DEFAULT CURRENT_TIMESTAMP AFTER `USERINSERT`,
ADD COLUMN `USERCHANGE` int DEFAULT NULL AFTER `DATEINSERT`,
ADD COLUMN `DATECHANGE` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP AFTER `USERCHANGE`,
ADD COLUMN `STATUS` char(1) DEFAULT 'A' AFTER `DATECHANGE`;

-- 27. ADICIONAR CAMPOS NA TABELA CAT_SERVICO
-- =====================================================
ALTER TABLE `CAT_SERVICO` 
ADD COLUMN `SITUACAO_TRIBUTARIA` int DEFAULT NULL AFTER `VALORUNITARIO`,
ADD COLUMN `TRIBUTA_MUNICIPIO_PRESTADOR` char(1) DEFAULT NULL COMMENT '0 quando a tributação ocorre no local da prestação do serviço 1 quando a tributação ocorre no município do prestador' AFTER `SITUACAO_TRIBUTARIA`;

-- admsis_concreta.CAT_SERVICO definição

CREATE TABLE `CAT_SERVICO` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `DESCRICAO` varchar(60) NOT NULL,
  `UNIDADE` varchar(3) NOT NULL,
  `QUANTIDADE` decimal(6,2) DEFAULT NULL,
  `VALORUNITARIO` decimal(8,2) NOT NULL,
  `STATUS` tinyint(1) NOT NULL DEFAULT '1' COMMENT '0 - Inativo, 1 - Ativo',
  `CREATED_USER` int DEFAULT NULL,
  `UPDATED_USER` int DEFAULT NULL,
  `CREATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `UPDATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
);
-- 28. CRIAR TABELA EST_NOTA_FISCAL_SERVICO_EVENTOS
-- =====================================================
CREATE TABLE `EST_NOTA_FISCAL_SERVICO_EVENTOS` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `ID_NFS` int NOT NULL,
  `CENTRO_CUSTO` varchar(11) NOT NULL,
  `SERIE` varchar(3) DEFAULT NULL,
  `NUMERO` int DEFAULT NULL,
  `TIPO_EVENTO` char(1) DEFAULT NULL COMMENT 'C - Cancelamento, E - Emissão, S - Solicitação de cancelamento (após o prazo), N - Consulta de NFS',
  `CODIGO_RETORNO` varchar(10) DEFAULT NULL,
  `XML_RETORNO` text,
  `CREATED_USER` int DEFAULT NULL,
  `CREATED_AT` timestamp DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
);

-- 29. CRIAR TABELA EST_SERVICOS_CODIGOS
-- =====================================================
CREATE TABLE `EST_SERVICOS_CODIGOS` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `CODIGO` varchar(10) NOT NULL,
  `SERVICO` text NOT NULL,
  `ALIQUOTA` decimal(5,2) NOT NULL,
  `RETENCAO` char(1) NOT NULL COMMENT '0 - Não, 1 - Sim',
  `RETENCAO_LEI_189_25` char(1) NOT NULL COMMENT '0 - Não, 1 - Sim',
  `OBRAS` char(1) NOT NULL COMMENT '0 - Não, 1 - Sim',
  `UF` varchar(2) NOT NULL,
  `COD_MUNICIPIO` varchar(10) NOT NULL,
  `MUNICIPIO` varchar(30) NOT NULL,
  `CREATED_USER` int DEFAULT NULL,
  `CREATED_AT` datetime DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_USER` int DEFAULT NULL,
  `UPDATED_AT` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
);

-- 30. CRIAR TABELA EST_NOTA_FISCAL_SERVICO
-- =====================================================
CREATE TABLE `EST_NOTA_FISCAL_SERVICO` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `IDENTIFICADOR_ARQUIVO` varchar(80) DEFAULT NULL UNIQUE,
  `NUMERO` int DEFAULT NULL,
  `SERIE` int DEFAULT NULL,
  `DATA_EMISSAO` date DEFAULT NULL,
  `HORA_EMISSAO` time DEFAULT NULL,
  `COD_VERIFICADOR_AUTENTICIDADE` varchar(16) DEFAULT NULL,
  `LINK_NFSE` varchar(500) DEFAULT NULL,
  `SITUACAO` int(1) DEFAULT NULL COMMENT '1-Emitida / 2-Cancelada',
  `RPS_NUMERO` varchar(9) DEFAULT NULL,
  `RPS_SERIE` varchar(2) DEFAULT NULL,
  `RPS_DATA_EMISSAO` date DEFAULT NULL,
  `RPS_HORA_EMISSAO` time DEFAULT NULL,
  `COD_EQUIPAMENTO_AUTOMATICO` varchar(100) DEFAULT NULL,
  `DATA_FATO_GERADOR` date DEFAULT NULL,
  `OBSERVACAO` varchar(1000) DEFAULT NULL,
  `VALOR_TOTAL` decimal(15,2) NOT NULL DEFAULT 0.00,
  `VALOR_DESCONTO` decimal(15,2) NOT NULL DEFAULT 0.00,
  `VALOR_IR` decimal(15,2) NOT NULL DEFAULT 0.00,
  `VALOR_INSS` decimal(15,2) NOT NULL DEFAULT 0.00,
  `VALOR_CONTRIBUICAO_SOCIAL` decimal(15,2) NOT NULL DEFAULT 0.00,
  `VALOR_RPS_RETENCAO` decimal(15,2) NOT NULL DEFAULT 0.00,
  `VALOR_PIS` decimal(15,2) NOT NULL DEFAULT 0.00,
  `VALOR_COFINS` decimal(15,2) NOT NULL DEFAULT 0.00,
  `PRESTADOR_CPFCNPJ` varchar(14) DEFAULT NULL,
  `PRESTADOR_CIDADE_CODIGO` int DEFAULT NULL,
  `TOMADOR_ID` int NOT NULL,
  `TOMADOR_CPFCNPJ` varchar(14) DEFAULT NULL,
  `TOMADOR_TIPO` char(1) DEFAULT NULL COMMENT 'F-Física / J-Jurídica / E-Estrangeiro',
  `TOMADOR_NOME_RAZAO_SOCIAL` varchar(100) DEFAULT NULL,
  `TOMADOR_NOME_FANTASIA` varchar(100) DEFAULT NULL,
  `TOMADOR_IE` varchar(16) DEFAULT NULL,
  `TOMADOR_EMAIL` varchar(100) DEFAULT NULL,
  `TOMADOR_ENDERECO_INFORMADO` char(1) DEFAULT NULL COMMENT '1-Sim / 0-Não',
  `TOMADOR_LOGRADOURO` varchar(70) DEFAULT NULL,
  `TOMADOR_NUMERO_RESIDENCIA` varchar(8) DEFAULT NULL,
  `TOMADOR_COMPLEMENTO` varchar(50) DEFAULT NULL,
  `TOMADOR_BAIRRO` varchar(30) DEFAULT NULL,
  `TOMADOR_CIDADE_CODIGO` varchar(100) DEFAULT NULL,
  `TOMADOR_CEP` varchar(8) DEFAULT NULL,
  `TOMADOR_PONTO_REFERENCIA` varchar(100) DEFAULT NULL,
  `TOMADOR_DDD_FONE_COMERCIAL` varchar(3) DEFAULT NULL,
  `TOMADOR_FONE_COMERCIAL` varchar(9) DEFAULT NULL,
  `TOMADOR_DDD_FONE_RESIDENCIAL` varchar(3) DEFAULT NULL,
  `TOMADOR_FONE_RESIDENCIAL` varchar(9) DEFAULT NULL,
  `TOMADOR_DDD_FAX` varchar(3) DEFAULT NULL,
  `TOMADOR_FONE_FAX` varchar(9) DEFAULT NULL,
  `TOMADOR_IDENTIFICADOR_ESTRANGEIRO` varchar(20) DEFAULT NULL,
  `TOMADOR_ESTADO_ESTRANGEIRO` varchar(100) DEFAULT NULL,
  `TOMADOR_PAIS_ESTRANGEIRO` varchar(100) DEFAULT NULL,
  `PRODUTOS_DESCRICAO` varchar(200) DEFAULT NULL COMMENT 'Tudo que se quer que saia na nota a respeito dos produtos',
  `PRODUTOS_VALOR_TOTAL` decimal(15,2) NOT NULL DEFAULT 0.00,
  `FORMA_PAGAMENTO_TIPO` int DEFAULT NULL COMMENT '1-À vista / 2-A prazo / 3-Na Apresentação / 4-Cartão de Débito / 5-Cartão de Crédito',
  `CREATED_USER` int NOT NULL,
  `CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_USER` int DEFAULT NULL,
  `UPDATED_AT` timestamp NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
);

-- 31. CRIAR TABELA EST_NOTA_FISCAL_SERVICO_ITEM
-- =====================================================
CREATE TABLE `EST_NOTA_FISCAL_SERVICO_ITEM` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `ID_NOTA_FISCAL_SERVICO` int NOT NULL,
  `ID_CAT_SERVICO` int NOT NULL,
  `TRIBUTA_MUNICIPIO_PRESTADOR` char(1) DEFAULT NULL COMMENT '1-Sim (tributação ocorre no município do prestador) / 0-Não (tributação ocorre no local da prestação do serviço)',
  `CODIGO_LOCAL_PRESTACAO_SERVICO` int DEFAULT NULL,
  `CODIGO_ITEM_LISTA_SERVICO` varchar(9) DEFAULT NULL,
  `DESCRITIVO` varchar(1000) DEFAULT NULL,
  `ALIQUOTA` decimal(5,2) NOT NULL DEFAULT 0.00,
  `SITUACAO_TRIBUTARIA` int DEFAULT NULL,
  `VALOR_TRIBUTAVEL` decimal(15,2) NOT NULL DEFAULT 0.00,
  `VALOR_DEDUCAO` decimal(15,2) NOT NULL DEFAULT 0.00,
  `VALOR_ISSRF` decimal(15,2) NOT NULL DEFAULT 0.00,
  `UNIDADE_CODIGO` int DEFAULT NULL,
  `UNIDADE_QUANTIDADE` decimal(15,2) DEFAULT NULL,
  `UNIDADE_VALOR_UNITARIO` decimal(15,2) NOT NULL DEFAULT 0.00,
  `CREATED_USER` int NOT NULL,
  `CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_USER` int DEFAULT NULL,
  `UPDATED_AT` timestamp NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `fk_EST_NOTA_FISCAL_SERVICO_ITEM_EST_NOTA_FISCAL_SERVICO1_idx` (`ID_NOTA_FISCAL_SERVICO`),
  KEY `fk_EST_NOTA_FISCAL_SERVICO_ITEM_CAT_SERVICO1_idx` (`ID_CAT_SERVICO`),
  CONSTRAINT `fk_EST_NOTA_FISCAL_SERVICO_ITEM_EST_NOTA_FISCAL_SERVICO1` FOREIGN KEY (`ID_NOTA_FISCAL_SERVICO`) REFERENCES `EST_NOTA_FISCAL_SERVICO` (`ID`),
  CONSTRAINT `fk_EST_NOTA_FISCAL_SERVICO_ITEM_CAT_SERVICO1` FOREIGN KEY (`ID_CAT_SERVICO`) REFERENCES `CAT_SERVICO` (`ID`)
);

-- 32. CRIAR TABELA CAT_AT_EQUIPE
-- =====================================================
CREATE TABLE `CAT_AT_EQUIPE` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `CAT_ATENDIMENTO_ID` int NOT NULL,
  `EQUIPE_EQUIPAMENTO_ID` int NOT NULL,
  `CAT_USUARIO_ID` int NOT NULL,
  `CREATED_USER` int DEFAULT NULL,
  `UPDATED_USER` int DEFAULT NULL,
  `CREATED_AT` timestamp DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb3;

-- 33. ADICIONAR CAMPOS ADICIONAIS NA TABELA FAT_PEDIDO
-- =====================================================
ALTER TABLE `FAT_PEDIDO` 
ADD COLUMN `ODESFERICO` varchar(10) DEFAULT NULL AFTER `IDAGRUPAMENTO`,
ADD COLUMN `OEESFERICO` varchar(10) DEFAULT NULL AFTER `ODESFERICO`,
ADD COLUMN `ODCILINDRICO` varchar(10) DEFAULT NULL AFTER `OEESFERICO`,
ADD COLUMN `OECILINDRICO` varchar(10) DEFAULT NULL AFTER `ODCILINDRICO`,
ADD COLUMN `ODEIXO` varchar(10) DEFAULT NULL AFTER `OECILINDRICO`,
ADD COLUMN `OEEIXO` varchar(10) DEFAULT NULL AFTER `ODEIXO`,
ADD COLUMN `ODAD` varchar(10) DEFAULT NULL AFTER `OEEIXO`,
ADD COLUMN `OEAD` varchar(10) DEFAULT NULL AFTER `ODAD`,
ADD COLUMN `MEDICO` varchar(60) DEFAULT NULL AFTER `OEAD`,
ADD COLUMN `OPORTUNIDADE` text DEFAULT NULL AFTER `MEDICO`,
ADD COLUMN `APRESENTACAO` text DEFAULT NULL AFTER `OPORTUNIDADE`,
ADD COLUMN `OBJETIVO` text DEFAULT NULL AFTER `APRESENTACAO`,
ADD COLUMN `GARANTIA` text DEFAULT NULL AFTER `OBJETIVO`,
ADD COLUMN `IMPOSTOS` text DEFAULT NULL AFTER `GARANTIA`,
ADD COLUMN `VALIDADE` text DEFAULT NULL AFTER `IMPOSTOS`,
ADD COLUMN `ACEITE` text DEFAULT NULL AFTER `VALIDADE`;

-- 34. ADICIONAR CAMPO PRECCREDITOSIMPLES NA TABELA EST_NAT_OP
-- =====================================================
ALTER TABLE `EST_NAT_OP` 
ADD COLUMN `PRECCREDITOSIMPLES` decimal(5,2) DEFAULT NULL AFTER `TRIBSIMPLES`;

-- 35. ADICIONAR CAMPO ANP NA TABELA EST_PRODUTO
-- =====================================================
ALTER TABLE `EST_PRODUTO` 
ADD COLUMN `ANP` text DEFAULT NULL AFTER `PERCCALCULO`;

-- 36. ALTERAR CAMPO GENERO PARA VARCHAR(6) NA TABELA FIN_LANCAMENTO
-- =====================================================
ALTER TABLE `FIN_LANCAMENTO` 
MODIFY COLUMN `GENERO` varchar(6) NOT NULL;

-- 37. ADICIONAR CAMPO CASASDECIMAIS NA TABELA FAT_PARAMETRO
-- =====================================================
ALTER TABLE `FAT_PARAMETRO` 
ADD COLUMN `TIPODESCONTO` char(1) DEFAULT 'T' AFTER `LANCPEDBAIXADO`;

ALTER TABLE `FAT_PARAMETRO` 
ADD COLUMN `CASASDECIMAIS` int DEFAULT 4 NOT NULL AFTER `TIPODESCONTO`;


-- 38. CRIAR TABELA AMB_RESPONSAVEL_TECNICO
-- =====================================================

CREATE TABLE `AMB_RESPONSAVEL_TECNICO` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(100) NOT NULL COMMENT 'NOME COMPLETO DO RESPONSÁVEL TÉCNICO',
  `CPF` VARCHAR(14) DEFAULT NULL COMMENT 'CPF DO RESPONSÁVEL TÉCNICO',
  `CREA` VARCHAR(20) DEFAULT NULL COMMENT 'NÚMERO DO CREA',
  `TELEFONE` VARCHAR(20) DEFAULT NULL COMMENT 'TELEFONE DE CONTATO',
  `EMAIL` VARCHAR(100) DEFAULT NULL COMMENT 'E-MAIL DE CONTATO',
  `CEP` VARCHAR(10) DEFAULT NULL COMMENT 'CEP',
  `RUA` VARCHAR(200) DEFAULT NULL COMMENT 'RUA',
  `NUMERO` VARCHAR(10) DEFAULT NULL COMMENT 'NÚMERO',
  `COMPLEMENTO` VARCHAR(100) DEFAULT NULL COMMENT 'COMPLEMENTO',
  `ESTADO` VARCHAR(2) DEFAULT NULL COMMENT 'ESTADO (UF)',
  `CIDADE` VARCHAR(50) DEFAULT NULL COMMENT 'CIDADE',
  `SITUACAO` CHAR(1) NOT NULL DEFAULT 'A' COMMENT 'SITUAÇÃO: A=ATIVO, I=INATIVO',
  `CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'DATA DE CADASTRO',
  `UPDATED_AT` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT 'DATA DA ÚLTIMA ALTERAÇÃO',
  `CREATED_BY` INT(11) DEFAULT NULL COMMENT 'USUÁRIO QUE CADASTROU',
  `UPDATED_BY` INT(11) DEFAULT NULL COMMENT 'USUÁRIO QUE ALTEROU',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_CPF` (`CPF`),
  UNIQUE KEY `UK_CREA` (`CREA`),
  KEY `IDX_NOME` (`NOME`),
  KEY `IDX_SITUACAO` (`SITUACAO`)
);

-- 39. INCLUIR DIREITO NO AMB_USUARIO_AUTORIZA
-- =====================================================
INSERT INTO `AMB_USUARIO_AUTORIZA` (`usuario`, `programa`, `direitos`) VALUES (999, 'AMBRESPONSAVELTECNICO', 'IAECSR');


-- 40. ALTERAR TABELA FAT_PEDIDO PARA ADICIONAR O CAMPO RESP_TECNICO
-- =====================================================
ALTER TABLE `FAT_PEDIDO` 
ADD COLUMN `RESP_TECNICO` int NULL AFTER `OBRA_ID`;


-- 41. ALTERAR TABELA EST_NOTA_FISCAL PARA ADICIONAR OS CAMPOS CODANTT E UF
-- =====================================================
ALTER TABLE `EST_NOTA_FISCAL` 
ADD COLUMN `CODANTT` VARCHAR(20) AFTER `PLACAVEICULO`,
ADD COLUMN `UF` VARCHAR(2) AFTER `CODANTT`;

-- 42. ALTERAR TABELA FAT_PEDIDO PARA ADICIONAR O CAMPO ENDERECOENTREGA
-- =====================================================
ALTER TABLE `FAT_PEDIDO` 
ADD COLUMN `ENDERECOENTREGA` int NULL AFTER `MODFRETE`;

-- 43. ALTERAR TABELA FAT_PARAMETRO PARA ADICIONAR O CAMPO CONTROLEVENDEDOR
-- =====================================================
ALTER TABLE `FAT_PARAMETRO` 
ADD COLUMN `CONTROLEVENDEDOR` int(1) DEFAULT '0' COMMENT '1=Controla vendedor, 0=Não controla';

-- 44. ALTERAR TABELA FIN_CLIENTE PARA ADICIONAR O CAMPO EMAILNFE
ALTER TABLE FIN_CLIENTE 
MODIFY COLUMN EMAILNFE TEXT NULL;

-- 45. ALTERAR TABELA FIN_CLIENTE PARA ADICIONAR O CAMPO CEP
-- =====================================================
ALTER TABLE FIN_CLIENTE
MODIFY COLUMN CEP VARCHAR(11) NULL;


-- 45. DIREITO PARA ALTERAR VENDEDOR NO PEDIDO
INSERT INTO AMB_FORM
(NOMEFORM, DESCRICAO, HELP)
VALUES('PEDPERMITEALTERARVENDEDOR', 'PEDIDO->PERMITE ALTERAR VENDEDOR', NULL);

INSERT INTO AMB_USUARIO_AUTORIZA
(USUARIO, PROGRAMA, DIREITOS)
VALUES(999, 'PEDPERMITEALTERARVENDEDOR', 'IAECSR');

--46
ALTER TABLE CAT_ATENDIMENTO
ADD COLUMN PEDIDO_ID int NULL AFTER `CAT_TIPO_ID`;

-- 47. ADICIONAR CAMPO NITEMPED NA TABELA EST_NOTA_FISCAL_PRODUTO
-- =====================================================
ALTER TABLE `EST_NOTA_FISCAL_PRODUTO` 
ADD COLUMN `NITEMPED` varchar(6) NULL AFTER `ORDEM`;

-- 48. adicionar no fat_pedido_item o campo NITEMPED
-- =====================================================
ALTER TABLE `FAT_PEDIDO_ITEM` 
ADD COLUMN `NITEMPED` varchar(6) NULL AFTER `NRITEM`;

-- 49. adicionar no fat_pedido_item o campo DATAENTREGA
-- =====================================================
ALTER TABLE `FAT_PEDIDO_ITEM` 
ADD COLUMN `DATAENTREGAPECA` date NULL AFTER `NITEMPED`;

-- 50. reposicionar NUMEROOC antes de NITEMPED na tabela FAT_PEDIDO_ITEM
-- =====================================================
ALTER TABLE `FAT_PEDIDO_ITEM` 
MODIFY COLUMN `NUMEROOC` varchar(20) NULL AFTER `NRITEM`;

-- 51. ADICIONAR CAMPOS PARA IBS/CBS (Imposto sobre Bens e Serviços / Contribuição sobre Bens e Serviços)
-- Implementado conforme NT 2024.001 - Homologação Receita Federal
-- =====================================================
ALTER TABLE `EST_NOTA_FISCAL_PRODUTO` 
ADD COLUMN `CSTIBSCBS` varchar(2) NULL DEFAULT '00' AFTER `VALORCOFINS`,
ADD COLUMN `CCLASSTRIB` varchar(2) NULL DEFAULT '01' AFTER `CSTIBSCBS`,
ADD COLUMN `BCIBSCBS` decimal(11,2) NULL DEFAULT 0.00 AFTER `CCLASSTRIB`,
ADD COLUMN `PIBSUF` decimal(5,2) NULL DEFAULT 0.00 AFTER `BCIBSCBS`,
ADD COLUMN `VIBSUF` decimal(11,2) NULL DEFAULT 0.00 AFTER `PIBSUF`,
ADD COLUMN `PIBSMUN` decimal(5,2) NULL DEFAULT 0.00 AFTER `VIBSUF`,
ADD COLUMN `VIBSMUN` decimal(11,2) NULL DEFAULT 0.00 AFTER `PIBSMUN`,
ADD COLUMN `PCBS` decimal(5,2) NULL DEFAULT 0.00 AFTER `VIBSMUN`,
ADD COLUMN `VCBS` decimal(11,2) NULL DEFAULT 0.00 AFTER `PCBS`;

-- 52. ADICIONAR CAMPOS PARA IBS/CBS NA TABELA EST_NAT_OP_TRIBUTO
-- Implementado conforme NT 2024.001 - Homologação Receita Federal
-- =====================================================
ALTER TABLE `EST_NAT_OP_TRIBUTO` 
ADD COLUMN `CSTIBSCBS` varchar(2) NULL DEFAULT '00' AFTER `ALIQCOFINS`,
ADD COLUMN `CCLASSTRIB` varchar(2) NULL DEFAULT '01' AFTER `CSTIBSCBS`,
ADD COLUMN `ALIQIBSUF` decimal(5,2) NULL DEFAULT 0.00 AFTER `CCLASSTRIB`,
ADD COLUMN `ALIQIBSMUN` decimal(5,2) NULL DEFAULT 0.00 AFTER `ALIQIBSUF`,
ADD COLUMN `ALIQCBS` decimal(5,2) NULL DEFAULT 0.00 AFTER `ALIQIBSMUN`;


-- 53. ADICIONAR CAMPOS PARA FAT_PEDIDO_SERVICO_ID NA TABELA CAT_AT_SERVICOS
-- =====================================================
-- Script para adicionar campo FAT_PEDIDO_SERVICO_ID na tabela CAT_AT_SERVICOS
-- Este campo relaciona o serviço da OS com o serviço do pedido
ALTER TABLE `CAT_AT_SERVICOS` 
ADD COLUMN `FAT_PEDIDO_SERVICO_ID` INT NULL DEFAULT NULL AFTER `CAT_SERVICOS_ID`,
ADD INDEX `fk_CAT_AT_SERVICOS_FAT_PEDIDO_SERVICO_idx` (`FAT_PEDIDO_SERVICO_ID`),
ADD CONSTRAINT `fk_CAT_AT_SERVICOS_FAT_PEDIDO_SERVICO` 
    FOREIGN KEY (`FAT_PEDIDO_SERVICO_ID`) 
    REFERENCES `FAT_PEDIDO_SERVICO` (`ID`) 
    ON DELETE SET NULL 
    ON UPDATE CASCADE;


-- 54. ADICIONAR CAMPO MARCA NA TABELA EST_PRODUTO_EQUIVALENCIA
-- =====================================================
ALTER TABLE `EST_PRODUTO_EQUIVALENCIA` 
ADD COLUMN `MARCA` VARCHAR(4) NULL DEFAULT NULL AFTER `CONTA`;

-- 55. ADICIONAR CAMPO PORT NA TABELA AMB_USUARIO
-- =====================================================
ALTER TABLE `AMB_USUARIO` 
ADD COLUMN `PORT` INT DEFAULT NULL AFTER `SMTP`;

-- 56. ADICIONAR CAMPO CODMUNICIPIO NA TABELA FIN_CLIENTE_ENDERECO
-- =====================================================
ALTER TABLE `FIN_CLIENTE_ENDERECO` 
ADD COLUMN `CODMUNICIPIO` VARCHAR(10) DEFAULT NULL 
AFTER `UF`;

-- 57. ADICIONAR CAMPO CCLASSTRIB NA TABELA EST_PRODUTO
-- =====================================================
ALTER TABLE `EST_PRODUTO` 
ADD COLUMN `CCLASSTRIB` varchar(15) DEFAULT NULL AFTER `CEST`;

-- 58. CRIAR TABELA EST_CCLASS_TRIB
-- =====================================================
CREATE TABLE `EST_CCLASS_TRIB` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `CCLASSTRIB` varchar(6) DEFAULT NULL,
  `NOME` varchar(100) DEFAULT NULL,
  `DESCRICAO` varchar(260) DEFAULT NULL,
  `CST` varchar(3) DEFAULT NULL,
  `LC_REDACAO` TEXT DEFAULT NULL,
  `LC_214_25` varchar(20) DEFAULT NULL,
  `TIPO_ALIQUOTA` varchar(32) DEFAULT NULL,
  `PRED_IBS` INT DEFAULT NULL,
  `PRED_CBS` INT DEFAULT NULL,
  `IND_G_TRIB_REGULAR` INT DEFAULT NULL,
  `IND_G_CRED_PRES_OPER` INT DEFAULT NULL,
  `IND_G_MONO_PADRAO` INT DEFAULT NULL,
  `IND_G_MONO_RETEN` INT DEFAULT NULL,
  `IND_G_MONO_RET` INT DEFAULT NULL,
  `IND_G_MONO_DIF` INT DEFAULT NULL,
  `IND_G_ESTORNO_CRED` INT DEFAULT NULL,
  `D_INI_VIG` DATE DEFAULT NULL,
  `D_FIM_VIG` DATE DEFAULT NULL,
  `DATA_ATUALIZACAO` DATE DEFAULT NULL,
  `IND_NFE_ABI` INT DEFAULT NULL,
  `IND_NFE` INT DEFAULT NULL,
  `IND_NF_CE` INT DEFAULT NULL,
  `IND_CTE` INT DEFAULT NULL,
  `IND_CTE_OS` INT DEFAULT NULL,
  `IND_BPE` INT DEFAULT NULL,
  `IND_BPE_TA` INT DEFAULT NULL,
  `IND_BPE_TM` INT DEFAULT NULL,
  `IND_NF_3E` INT DEFAULT NULL,
  `IND_NFSE` INT DEFAULT NULL,
  `IND_NFSE_VIA` INT DEFAULT NULL,
  `IND_NF_COM` INT DEFAULT NULL,
  `IND_NF_AG` INT DEFAULT NULL,
  `IND_NF_GAS` INT DEFAULT NULL,
  `IND_DERE` INT DEFAULT NULL,
  `CREATED_AT` timestamp DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `CREATED_USER` int DEFAULT NULL,
  `UPDATED_USER` int DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_CCLASSTRIB` (`CCLASSTRIB`),
  KEY `FK_CST` (`CST`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


-- 59. CRIAR TABELA EST_CST_IBS_CBS
-- =====================================================
CREATE TABLE `EST_CST_IBS_CBS` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `CST` varchar(3) DEFAULT NULL,
  `DESCRICAO` TEXT DEFAULT NULL,
  `IND_G_IBS_CBS` INT DEFAULT NULL,
  `IND_G_IBS_CBS_MONO` INT DEFAULT NULL,
  `IND_G_RED` INT DEFAULT NULL,
  `IND_G_DIF` INT DEFAULT NULL,
  `IND_G_TRANSF_CRED` INT DEFAULT NULL,
  `IND_G_CRED_PRES_IBS_ZFM` INT DEFAULT NULL,
  `IND_G_AJUSTE_COMPET` INT DEFAULT NULL,
  `IND_REDUTOR_BC` INT DEFAULT NULL,
  `CREATED_AT` timestamp DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `CREATED_USER` int DEFAULT NULL,
  `UPDATED_USER` int DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_CST` (`CST`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


-- 60. ADICIONAR FOREIGN KEY ENTRE EST_CCLASS_TRIB E EST_CST_IBS_CBS
-- =====================================================
ALTER TABLE `EST_CCLASS_TRIB`
ADD FOREIGN KEY (`CST`) REFERENCES `EST_CST_IBS_CBS` (`CST`) 
ON DELETE SET NULL ON UPDATE CASCADE;


-- 61. CRIAR TABELA EST_NATUREZA_OPERACAO_TRIBUTO_IBS_CBS
-- =====================================================
CREATE TABLE `EST_NATUREZA_OPERACAO_TRIBUTO_IBS_CBS` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `ID_EST_NAT_OP` int DEFAULT NULL,
  `UF_DEST` varchar(2) DEFAULT NULL,
  `MUN_DEST` varchar(100) DEFAULT NULL,
  `COD_MUN_DEST` varchar(10) DEFAULT NULL,
  `TIPO_PESSOA` varchar(1) DEFAULT NULL,
  `CCLASSTRIB` varchar(6) DEFAULT NULL,
  `NCM` varchar(10) DEFAULT NULL,
  `ALIQUOTA_IBS_UF` decimal(5,2) DEFAULT NULL,
  `ALIQUOTA_IBS_MUN` decimal(5,2) DEFAULT NULL,
  `ALIQUOTA_CBS` decimal(5,2) DEFAULT NULL,
  `CREATED_AT` timestamp DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `CREATED_USER` int DEFAULT NULL,
  `UPDATED_USER` int DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_ID_EST_NAT_OP` (`ID_EST_NAT_OP`),
  KEY `FK_CCLASSTRIB` (`CCLASSTRIB`),
  KEY `FK_NCM` (`NCM`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 62. INCLUIR DIREITO NO AMB_USUARIO_AUTORIZA
-- =====================================================
INSERT INTO `AMB_FORM` (`nomeform`, `descricao`, `help`) VALUES ('EstCstIbsCbs', 'CADASTROSGERAIS->CST_IBS_CBS', NULL);
INSERT INTO `AMB_FORM` (`nomeform`, `descricao`, `help`) VALUES ('EstCclasstrib', 'CADASTROSGERAIS->CCLASSTRIB', NULL);
INSERT INTO `AMB_FORM` (`nomeform`, `descricao`, `help`) VALUES ('EstTribIbsCbs', 'CADASTROSGERAIS->EstTribIbsCbs', NULL);
INSERT INTO `AMB_USUARIO_AUTORIZA` (`usuario`, `programa`, `direitos`) VALUES (999, 'EstCstIbsCbs', 'IAECSR');
INSERT INTO `AMB_USUARIO_AUTORIZA` (`usuario`, `programa`, `direitos`) VALUES (999, 'EstCclasstrib', 'IAECSR');
INSERT INTO `AMB_USUARIO_AUTORIZA` (`usuario`, `programa`, `direitos`) VALUES (999, 'EstTribIbsCbs', 'IAECSR');


-- 63. CRIAR TABELA EST_NOTA_FISCAL_PRODUTO_TRIBUTOS (IBS/CBS)
-- =====================================================
CREATE TABLE `EST_NOTA_FISCAL_PRODUTO_TRIBUTOS` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `ID_NOTA_FISCAL` int DEFAULT NULL COMMENT 'FK para EST_NOTA_FISCAL',
  `ID_NOTA_FISCAL_PRODUTO` int DEFAULT NULL COMMENT 'FK para EST_NOTA_FISCAL_PRODUTO',
  -- gTribRegular (Tributação Regular)
  `CST_REG` varchar(3) DEFAULT NULL COMMENT 'CST para tributação regular IBS/CBS',
  `C_CLASS_TRIB_REG` varchar(10) DEFAULT NULL COMMENT 'Código de classificação tributária regular',
  `P_ALIQ_EFET_REG_IBS_UF` decimal(7,4) DEFAULT NULL COMMENT 'Percentual alíquota efetiva IBS UF',
  `V_TRIB_REG_IBS_UF` decimal(15,2) DEFAULT NULL COMMENT 'Valor tributo IBS UF',
  `P_ALIQ_EFET_REG_IBS_MUN` decimal(7,4) DEFAULT NULL COMMENT 'Percentual alíquota efetiva IBS Municipal',
  `V_TRIB_REG_IBS_MUN` decimal(15,2) DEFAULT NULL COMMENT 'Valor tributo IBS Municipal',
  `P_ALIQ_EFET_REG_CBS` decimal(7,4) DEFAULT NULL COMMENT 'Percentual alíquota efetiva CBS',
  `V_TRIB_REG_CBS` decimal(15,2) DEFAULT NULL COMMENT 'Valor tributo CBS',  
  -- gCredPresOper (Crédito Presumido da Operação)
  `V_BC_CRED_PRES` decimal(15,2) DEFAULT NULL COMMENT 'Valor base de cálculo do crédito presumido',
  `C_CRED_PRES` varchar(10) DEFAULT NULL COMMENT 'Código do crédito presumido',  
  -- gMonoPadrao (Monofásico Padrão)
  `Q_BC_MONO` decimal(15,4) DEFAULT NULL COMMENT 'Quantidade base de cálculo monofásico',
  `AD_REM_IBS` decimal(15,4) DEFAULT NULL COMMENT 'Alíquota ad rem IBS',
  `AD_REM_CBS` decimal(15,4) DEFAULT NULL COMMENT 'Alíquota ad rem CBS',
  `V_IBS_MONO` decimal(15,2) DEFAULT NULL COMMENT 'Valor IBS monofásico',
  `V_CBS_MONO` decimal(15,2) DEFAULT NULL COMMENT 'Valor CBS monofásico',  
  -- gMonoReten (Monofásico com Retenção)
  `Q_BC_MONO_RETEN` decimal(15,4) DEFAULT NULL COMMENT 'Quantidade BC monofásico retenção',
  `AD_REM_IBS_RETEN` decimal(15,4) DEFAULT NULL COMMENT 'Alíquota ad rem IBS retenção',
  `V_IBS_MONO_RETEN` decimal(15,2) DEFAULT NULL COMMENT 'Valor IBS monofásico retenção',
  `AD_REM_CBS_RETEN` decimal(15,4) DEFAULT NULL COMMENT 'Alíquota ad rem CBS retenção',
  `V_CBS_MONO_RETEN` decimal(15,2) DEFAULT NULL COMMENT 'Valor CBS monofásico retenção',  
  -- gMonoRet (Monofásico Retido)
  `Q_BC_MONO_RET` decimal(15,4) DEFAULT NULL COMMENT 'Quantidade BC monofásico retido',
  `AD_REM_IBS_RET` decimal(15,4) DEFAULT NULL COMMENT 'Alíquota ad rem IBS retido',
  `V_IBS_MONO_RET` decimal(15,2) DEFAULT NULL COMMENT 'Valor IBS monofásico retido',
  `AD_REM_CBS_RET` decimal(15,4) DEFAULT NULL COMMENT 'Alíquota ad rem CBS retido',
  `V_CBS_MONO_RET` decimal(15,2) DEFAULT NULL COMMENT 'Valor CBS monofásico retido',  
  -- gMonoDif (Monofásico Diferido)
  `P_DIF_IBS` decimal(7,4) DEFAULT NULL COMMENT 'Percentual de diferimento IBS',
  `V_IBS_MONO_DIF` decimal(15,2) DEFAULT NULL COMMENT 'Valor IBS monofásico diferido',
  `P_DIF_CBS` decimal(7,4) DEFAULT NULL COMMENT 'Percentual de diferimento CBS',
  `V_TOT_IBS_MONO_ITEM` decimal(15,2) DEFAULT NULL COMMENT 'Valor total IBS monofásico do item',
  `V_TOT_CBS_MONO_ITEM` decimal(15,2) DEFAULT NULL COMMENT 'Valor total CBS monofásico do item',
  -- gEstornoCred (Estorno de Crédito)
  `V_IBS_EST_CRED` decimal(15,2) DEFAULT NULL COMMENT 'Valor IBS estorno de crédito',
  `V_CBS_EST_CRED` decimal(15,2) DEFAULT NULL COMMENT 'Valor CBS estorno de crédito',
  
  -- Campos de controle
  `CREATED_AT` timestamp DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `CREATED_USER` int DEFAULT NULL,
  `UPDATED_USER` int DEFAULT NULL,
  
  PRIMARY KEY (`ID`),
  KEY `FK_ID_NOTA_FISCAL` (`ID_NOTA_FISCAL`),
  KEY `FK_ID_NOTA_FISCAL_PRODUTO` (`ID_NOTA_FISCAL_PRODUTO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Tributos IBS/CBS por produto da Nota Fiscal';

-- 64. ADICIONAR CAMPO XML NA TABELA EST_NOTA_FISCAL_EVENTOS
ALTER TABLE EST_NOTA_FISCAL_EVENTOS 
ADD COLUMN `XML` mediumtext DEFAULT NULL AFTER CSTAT;

-- 65. ADICIONAR CAMPO XMLCONFERIRESTOQUE NA TABELA EST_PARAMETRO
ALTER TABLE `EST_PARAMETRO` 
ADD COLUMN `XMLCONFERIRESTOQUE` CHAR(1) DEFAULT 'N' NOT NULL AFTER `PERCALCULO`;

-- 66. ADICIONAR CAMPOS FALTANTES NA TABELA EST_NOTA_FISCAL_PRODUTO
-- Campos necessários para captura completa de todas as tags do XML da NFe
-- =====================================================
ALTER TABLE `EST_NOTA_FISCAL_PRODUTO` 
ADD COLUMN `VALORTOTALTRIBUTOS` decimal(11,2) NULL DEFAULT 0.00 AFTER `VALORICMSST`,
ADD COLUMN `PST` decimal(5,2) NULL DEFAULT 0.00 AFTER `VCREDICMSSN`,
ADD COLUMN `QUANTBCPRODPIS` decimal(11,4) NULL DEFAULT 0.0000 AFTER `VALORPIS`,
ADD COLUMN `QUANTBCPRODCOFINS` decimal(11,4) NULL DEFAULT 0.0000 AFTER `VALORCOFINS`;

-- 67. ADICIONAR CAMPOS DE FCP NORMAL E ICMS DESONERADO
-- FCP Normal (diferente de FCP ST e FCP UFDest)
-- =====================================================
ALTER TABLE `EST_NOTA_FISCAL_PRODUTO` 
ADD COLUMN `VBCFCP` decimal(11,2) NULL DEFAULT 0.00 AFTER `VALORFCPUFDEST`,
ADD COLUMN `PFCP` decimal(5,2) NULL DEFAULT 0.00 AFTER `VBCFCP`,
ADD COLUMN `VFCP` decimal(11,2) NULL DEFAULT 0.00 AFTER `PFCP`,
ADD COLUMN `VICMSDESON` decimal(11,2) NULL DEFAULT 0.00 AFTER `VALORICMS`,
ADD COLUMN `MOTDESICMS` varchar(2) NULL DEFAULT NULL AFTER `VICMSDESON`;

-- 68. ADICIONAR CAMPOS DE IPI POR PAUTA
-- =====================================================
ALTER TABLE `EST_NOTA_FISCAL_PRODUTO` 
ADD COLUMN `QUNIDIPI` decimal(11,4) NULL DEFAULT 0.0000 AFTER `BCIPI`,
ADD COLUMN `VUNIDIPI` decimal(11,4) NULL DEFAULT 0.0000 AFTER `QUNIDIPI`;

-- 69. ADICIONAR CAMPOS DE IMPOSTO DE IMPORTAÇÃO
-- =====================================================
ALTER TABLE `EST_NOTA_FISCAL_PRODUTO` 
ADD COLUMN `VBCII` decimal(11,2) NULL DEFAULT 0.00 AFTER `VALORTOTALTRIBUTOS`,
ADD COLUMN `VDESPAU` decimal(11,2) NULL DEFAULT 0.00 AFTER `VBCII`,
ADD COLUMN `VII` decimal(11,2) NULL DEFAULT 0.00 AFTER `VDESPAU`,
ADD COLUMN `VIOF` decimal(11,2) NULL DEFAULT 0.00 AFTER `VII`;

-- 70. ADICIONAR CAMPOS DE CALCULO DE IPI E ST NO CUSTO DE REPOSIÇÃO
-- =====================================================
ALTER TABLE `EST_PARAMETRO` 
ADD COLUMN `CALCULA_IPI_CUSTO_REPOSICAO` CHAR(1) DEFAULT 'N' NOT NULL COMMENT 'S=Calcula IPI no custo de reposição, N=Não calcula' AFTER `PERCALCULO`,
ADD COLUMN `CALCULA_ST_CUSTO_REPOSICAO` CHAR(1) DEFAULT 'N' NOT NULL COMMENT 'S=Calcula ST no custo de reposição, N=Não calcula' AFTER `CALCULA_IPI_CUSTO_REPOSICAO`;

-- 71. ALTERAR COLUNA SITUACAO DA TABELA EST_NOTA_FISCAL PARA UTF8MB4'
ALTER TABLE EST_NOTA_FISCAL MODIFY COLUMN SITUACAO char(2) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL;

-- 72. ADICIONAR CAMPOS DE SITUACAO DO MANIFESTO FISCAL SEFAZ
INSERT INTO AMB_DDM
(ALIAS, NRCAMPO, CAMPO, TIPO, TAMANHO, DECIMAIS, FORMATO, REQUERIDO, PADRAO, LEGENDA, MASCARA, NOMEEXTERNO, ALTERACAO, DESCRICAO, `SQL`, MENSAGEM, MENU)
VALUES('EST_MENU', 229, 'SITUACAOMANIFESTOSEFAZ', 'CO', 0, 0, NULL, 'N', 'CONFIRMA OPERACAO', NULL, NULL, NULL, '2001-05-16', NULL, NULL, NULL, NULL);
INSERT INTO AMB_DDM
(ALIAS, NRCAMPO, CAMPO, TIPO, TAMANHO, DECIMAIS, FORMATO, REQUERIDO, PADRAO, LEGENDA, MASCARA, NOMEEXTERNO, ALTERACAO, DESCRICAO, `SQL`, MENSAGEM, MENU)
VALUES('EST_MENU', 230, 'SITUACAOMANIFESTOSEFAZ', 'DO', 0, 0, NULL, 'N', 'DESCONHECIMENTO DA OPERACAO', NULL, NULL, NULL, '2001-05-16', NULL, NULL, NULL, NULL);
INSERT INTO AMB_DDM
(ALIAS, NRCAMPO, CAMPO, TIPO, TAMANHO, DECIMAIS, FORMATO, REQUERIDO, PADRAO, LEGENDA, MASCARA, NOMEEXTERNO, ALTERACAO, DESCRICAO, `SQL`, MENSAGEM, MENU)
VALUES('EST_MENU', 231, 'SITUACAOMANIFESTOSEFAZ', 'OR', 0, 0, NULL, 'N', 'OPERACAO NAO REALIZADA', NULL, NULL, NULL, '2001-05-16', NULL, NULL, NULL, NULL);
INSERT INTO AMB_DDM
(ALIAS, NRCAMPO, CAMPO, TIPO, TAMANHO, DECIMAIS, FORMATO, REQUERIDO, PADRAO, LEGENDA, MASCARA, NOMEEXTERNO, ALTERACAO, DESCRICAO, `SQL`, MENSAGEM, MENU)
VALUES('EST_MENU', 232, 'SITUACAOMANIFESTOSEFAZ', 'NP', 0, 0, NULL, 'N', 'NAO PROCESSADA', NULL, NULL, NULL, '2001-05-16', NULL, NULL, NULL, NULL);

-- 73. ADICIONAR CAMPO NFENTRADA NA TABELA CAT_AT_PECA
-- =====================================================
ALTER TABLE `CAT_AT_PECAS` 
ADD COLUMN `NFENTRADA` int(11) DEFAULT NULL AFTER `CAT_ATENDIMENTO_ID`;

-- 74. ADICIONAR CAMPO XMLMANTERORIGEMCST NA TABELA EST_PARAMETRO
ALTER TABLE `EST_PARAMETRO` 
ADD COLUMN `XMLMANTERORIGEMCST` CHAR(1) DEFAULT 'S' NOT NULL AFTER `CALCULA_ST_CUSTO_REPOSICAO`;

-- 75. ADICIONAR CAMPO CODIGONOTA NA TABELA EST_NOTA_FISCAL_PRODUTO (código do produto na NF-e - cProd)
ALTER TABLE `EST_NOTA_FISCAL_PRODUTO` 
ADD COLUMN `CODIGONOTA` varchar(60) DEFAULT NULL AFTER `DESPACESSORIAS`;

-- 76. ADICIONAR CAMPO PRECOUNITARIO NA TABELA EST_PRODUTO_EQUIVALENCIA
ALTER TABLE `EST_PRODUTO_EQUIVALENCIA` 
ADD COLUMN `PRECOUNITARIO` decimal(11,2) NULL DEFAULT 0.00 AFTER `QUANTULTIMACOMPRA`;

-- 77. ADICIONAR CAMPOS NA TABELA EST_TABELA_PRECO_ITEM
-- =====================================================
ALTER TABLE `EST_TABELA_PRECO_ITEM` 
ADD COLUMN `DESCRICAO` varchar(90) NULL AFTER `CODIGO`,
ADD COLUMN `MARCA` varchar(9) NULL AFTER `DESCRICAO`,
ADD COLUMN `PRECOBASEANTERIOR` decimal(11,4) NULL AFTER `MARCA`,
ADD COLUMN `CODIGOFABRICANTE` VARCHAR(25) NULL AFTER `PRECOBASEANTERIOR`,
ADD COLUMN `ID_TABELA_PRECO` int DEFAULT NULL AFTER `ID`;

ALTER TABLE `EST_TABELA_PRECO_ITEM`
MODIFY COLUMN `CODIGO` int(11) NULL DEFAULT NULL;

ALTER TABLE EST_TABELA_PRECO ADD COLUMN `PESSOA` int DEFAULT NULL AFTER `MARGEM`;


-- 78. ALTERAR TABELA EST_MARCA PARA AUTO_INCREMENT E ADICIONAR CAMPOS DE CHAVE
-- =====================================================
CREATE TABLE `EST_MARCA_NEW` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `MARCA` VARCHAR(5) NOT NULL,
  `DESCRICAO` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_MARCA` (`MARCA`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

-- Copiar dados existentes
INSERT INTO `EST_MARCA_NEW` (`MARCA`, `DESCRICAO`)
SELECT `MARCA`, `DESCRICAO` FROM `EST_MARCA`;

-- Substituir tabela antiga
DROP TABLE `EST_MARCA`;
RENAME TABLE `EST_MARCA_NEW` TO `EST_MARCA`;

-- 
-- 79. ADICIONAR DIREITO NO AMB_USUARIO_AUTORIZA
-- =====================================================
INSERT INTO `AMB_FORM` (`nomeform`, `descricao`, `help`) VALUES ('TabelaPreco', 'CADASTROSGERAIS->TabelaPreco', NULL);
INSERT INTO `AMB_USUARIO_AUTORIZA` (`usuario`, `programa`, `direitos`) VALUES (999, 'TabelaPreco', 'IAECSR');


-- 80. ALTERAR COLUNA EMISSAO DA TABELA EST_NOTA_FISCAL PARA TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
-- =====================================================
ALTER TABLE EST_NOTA_FISCAL 
MODIFY COLUMN EMISSAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- 81. ADICIONAR SITUACAO EXTRATO NA TABELA AMB_DDM
INSERT INTO AMB_DDM (ALIAS,NRCAMPO,CAMPO,TIPO,TAMANHO,DECIMAIS,FORMATO,REQUERIDO,PADRAO,LEGENDA,MASCARA,NOMEEXTERNO,ALTERACAO,DESCRICAO,`SQL`,MENSAGEM,MENU) VALUES
	 ('FIN_MENU',30,'SITUACAOEXTRATO','A',0,0,'','N','A - ABERTO','',NULL,NULL,'2001-03-27',NULL,NULL,NULL,NULL),
	 ('FIN_MENU',31,'SITUACAOEXTRATO','B',0,0,'','N','B - BAIXADO','',NULL,NULL,'2001-03-27',NULL,NULL,NULL,NULL);

-- 82. CRIAR TABELA AMB_FERIADO

CREATE TABLE `AMB_FERIADO` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CENTROCUSTO` int(11) NOT NULL,
  `DATAFERIADO` date NOT NULL,
  `DESCRICAO` varchar(45) NOT NULL,
  `ESTADUAL` char(1) NOT NULL COMMENT '1 - ESTADUAL / 0 - MUNICIPAL',
  `CREATE_AT` timestamp NOT NULL DEFAULT current_timestamp(),
  `CREATE_USER` int(11) NOT NULL,
  `UPDATE_AT` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `UPDATE_USER` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- 83. ADICIONAR CAMPOS DE USUÁRIO E DATA DE ATUALIZAÇÃO E INSERÇÃO NA TABELA FIN_CLIENTE_CREDITO
-- =====================================================
ALTER TABLE FIN_CLIENTE_CREDITO
ADD COLUMN `USERUPDATE` int(11) DEFAULT NULL AFTER `PEDIDOUTILIZADO`,
ADD COLUMN `DATEUPDATE` timestamp NULL DEFAULT NULL AFTER `USERUPDATE`,
ADD COLUMN `USERINSERT` int(11) DEFAULT NULL AFTER `DATEUPDATE`,
ADD COLUMN `DATEINSERT` timestamp NULL DEFAULT current_timestamp() AFTER `USERINSERT`;

-- 84. DASHBOARDS 4.5 — AMB_FORM E AUTORIZAÇÃO (grupo 999)
-- Programas: PedidoDashboard, FinanceiroDashboard, EstoqueDashboard, CrmDashboard
-- Direitos na string DIREITOS (padrão IAECSR): I Incluir, A Alterar, E Excluir, C Consultar, S Relatório/serviços, R (reservado conforme cadastro de usuário)
-- Nos forms: consulta ao dashboard exige C; no CRM, motivoGeral (venda perdida) exige C e A
-- =====================================================
INSERT INTO `AMB_FORM` (`nomeform`, `descricao`, `help`) VALUES ('PedidoDashboard', 'PEDIDOS->DashboardPedidos', NULL);
INSERT INTO `AMB_USUARIO_AUTORIZA` (`usuario`, `programa`, `direitos`) VALUES (999, 'PedidoDashboard', 'IAECSR');

INSERT INTO `AMB_FORM` (`nomeform`, `descricao`, `help`) VALUES ('FinanceiroDashboard', 'FINANCEIRO->DashboardFinanceiro', NULL);
INSERT INTO `AMB_USUARIO_AUTORIZA` (`usuario`, `programa`, `direitos`) VALUES (999, 'FinanceiroDashboard', 'IAECSR');

INSERT INTO `AMB_FORM` (`nomeform`, `descricao`, `help`) VALUES ('EstoqueDashboard', 'ESTOQUE->DashboardEstoque', NULL);
INSERT INTO `AMB_USUARIO_AUTORIZA` (`usuario`, `programa`, `direitos`) VALUES (999, 'EstoqueDashboard', 'IAECSR');

INSERT INTO `AMB_FORM` (`nomeform`, `descricao`, `help`) VALUES ('CrmDashboard', 'CRM->DashboardCRM', NULL);
INSERT INTO `AMB_USUARIO_AUTORIZA` (`usuario`, `programa`, `direitos`) VALUES (999, 'CrmDashboard', 'IAECSR');

-- Direito interno: permite ver leads/acompanhamentos de outros vendedores/representantes
INSERT INTO `AMB_FORM` (`NOMEFORM`, `DESCRICAO`, `HELP`) VALUES ('CRMDASHVEROUTROSVENDEDORES', 'CRM->DASHBOARDCRM', NULL);
INSERT INTO `AMB_USUARIO_AUTORIZA` (`USUARIO`, `PROGRAMA`, `DIREITOS`) VALUES (999, 'CRMDASHBOARDVEROUTROSVENDEDORES', 'IAECSR');


-- 85. CRIAR TABELA AMB_TEMPLATE
-- =====================================================
CREATE TABLE `AMB_TEMPLATE` (
  `ID` int(11) NOT NULL,
  `DESCRICAO` varchar(30) DEFAULT NULL,
  `PARAMETRO` varchar(100) DEFAULT NULL,
  `BODY` text DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

ALTER TABLE `AMB_TEMPLATE`
  ADD PRIMARY KEY (`ID`);

INSERT INTO `AMB_FORM` (`NOMEFORM`, `DESCRICAO`, `HELP`) VALUES ('AmbTemplateEmail', 'UTILITARIOS->TemplateEmail', NULL);
INSERT INTO `AMB_USUARIO_AUTORIZA` (`USUARIO`, `PROGRAMA`, `DIREITOS`) VALUES (999, 'AmbTemplateEmail', 'IAECSR');

-- 86. CRIAR TABELA FIN_CLIENTE_CONTATO
-- =====================================================
CREATE TABLE `FIN_CLIENTE_CONTATO` (
  `ID` int(11) NOT NULL,
  `ID_CLIENTE` int(11) NOT NULL,
  `TELEFONE` varchar(20) DEFAULT NULL,
  `EMAIL` varchar(50) DEFAULT NULL,
  `NOME_CONTATO` varchar(100) DEFAULT NULL,
  `USERINSERT` int(11) DEFAULT NULL,
  `DATEINSERT` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

ALTER TABLE FIN_CLIENTE_CONTATO
ADD PRIMARY KEY (`ID`);

ALTER TABLE `FIN_CLIENTE_CONTATO`
  MODIFY `ID` int(11) NOT NULL AUTO_INCREMENT;

-- 87. FAT_PARAMETRO: redirecionar Pedido PS (cotação→pedido) para financeiro do Gerência Pedido Novo
-- =====================================================
ALTER TABLE `FAT_PARAMETRO`
ADD COLUMN `FATURAPEDIDO` char(1) NOT NULL DEFAULT 'N' COMMENT 'S=ao confirmar cotação no PS abre lançamento financeiro (gerente novo); N=não';

-- 87.1. FAT_PARAMETRO: controle de fluxo de encomenda nos parâmetros de pedido
-- =====================================================
ALTER TABLE `FAT_PARAMETRO`
ADD COLUMN `ENCOMENDA` char(1) NOT NULL DEFAULT 'N';


-- 88. ALTERAR COLUNA NOME DA TABELA FIN_CLIENTE PARA UTF8MB3
-- =====================================================
ALTER TABLE FIN_CLIENTE MODIFY COLUMN NOME varchar(60) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL;
ALTER TABLE FIN_CLIENTE MODIFY COLUMN NOMEREDUZIDO varchar(60) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL;


-- 89. SITUACAO ENCOMENDA (13) NO DOMINIO AMB_DDM — Pedido PS / fluxo encomenda
-- =====================================================
INSERT INTO AMB_DDM (ALIAS, NRCAMPO, CAMPO, TIPO, TAMANHO, DECIMAIS, FORMATO, REQUERIDO, PADRAO, LEGENDA, MASCARA, NOMEEXTERNO, ALTERACAO, DESCRICAO, `SQL`, MENSAGEM, MENU)
SELECT 'FAT_MENU', COALESCE(MAX(NRCAMPO), 0) + 1, 'SITUACAOPEDIDO', '13', 0, 0, NULL, 'N', 'ENCOMENDA', NULL, NULL, NULL, CURDATE(), 'Pedido faturado aguardando entrada de estoque', NULL, NULL, NULL
FROM AMB_DDM
WHERE ALIAS = 'FAT_MENU' AND CAMPO = 'SITUACAOPEDIDO'
  AND NOT EXISTS (SELECT 1 FROM AMB_DDM d WHERE d.ALIAS = 'FAT_MENU' AND d.CAMPO = 'SITUACAOPEDIDO' AND d.TIPO = '13');

-- 91. SITUACAO EM APROVACAO (10) NO DOMINIO AMB_DDM — Pedido PS / tela Pedido Aprovação
-- =====================================================
INSERT INTO AMB_DDM (ALIAS, NRCAMPO, CAMPO, TIPO, TAMANHO, DECIMAIS, FORMATO, REQUERIDO, PADRAO, LEGENDA, MASCARA, NOMEEXTERNO, ALTERACAO, DESCRICAO, `SQL`, MENSAGEM, MENU)
SELECT 'FAT_MENU', COALESCE(MAX(NRCAMPO), 0) + 1, 'SITUACAOPEDIDO', '10', 0, 0, NULL, 'N', 'EM APROVAÇÃO', NULL, NULL, NULL, CURDATE(), 'Pedido aguardando aprovação gerencial de desconto', NULL, NULL, NULL
FROM AMB_DDM
WHERE ALIAS = 'FAT_MENU'
  AND NOT EXISTS (SELECT 1 FROM AMB_DDM d WHERE d.ALIAS = 'FAT_MENU' AND d.CAMPO = 'SITUACAOPEDIDO' AND d.TIPO = '10');

-- 90. ADICIONAR CAMPO GENERO_EXTRATO NA TABELA EST_PARAMETRO
-- =====================================================
ALTER TABLE `EST_PARAMETRO`
ADD COLUMN `GENERO_EXTRATO` varchar(10) DEFAULT NULL AFTER `GENERO`;

-- 92. DIREITOS — PARÂMETROS PEDIDO, ESTOQUE E ORDEM DE SERVIÇO (AMB_FORM + grupo 999)
-- =====================================================
INSERT INTO `AMB_FORM` (`NOMEFORM`, `DESCRICAO`, `HELP`)
SELECT 'PedParametros', 'PEDIDOS->ParametrosPedidos', NULL
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `AMB_FORM` WHERE `NOMEFORM` = 'PedParametros');

INSERT INTO `AMB_FORM` (`NOMEFORM`, `DESCRICAO`, `HELP`)
SELECT 'EstParametros', 'ESTOQUE->ParametrosEstoque', NULL
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `AMB_FORM` WHERE `NOMEFORM` = 'EstParametros');

INSERT INTO `AMB_FORM` (`NOMEFORM`, `DESCRICAO`, `HELP`)
SELECT 'CatParametros', 'ORDEMSERVICO->ParametrosOS', NULL
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `AMB_FORM` WHERE `NOMEFORM` = 'CatParametros');

INSERT INTO `AMB_USUARIO_AUTORIZA` (`USUARIO`, `PROGRAMA`, `DIREITOS`)
SELECT 999, 'PedParametros', 'IAECSR'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `AMB_USUARIO_AUTORIZA` WHERE `USUARIO` = 999 AND `PROGRAMA` = 'PedParametros');

INSERT INTO `AMB_USUARIO_AUTORIZA` (`USUARIO`, `PROGRAMA`, `DIREITOS`)
SELECT 999, 'EstParametros', 'IAECSR'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `AMB_USUARIO_AUTORIZA` WHERE `USUARIO` = 999 AND `PROGRAMA` = 'EstParametros');

INSERT INTO `AMB_USUARIO_AUTORIZA` (`USUARIO`, `PROGRAMA`, `DIREITOS`)
SELECT 999, 'CatParametros', 'IAECSR'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `AMB_USUARIO_AUTORIZA` WHERE `USUARIO` = 999 AND `PROGRAMA` = 'CatParametros');


-- 93. DEVOLUÇÃO NF WIZARD - JUNHO-2026
-- =====================================================
INSERT INTO `AMB_FORM` (`NOMEFORM`, `DESCRICAO`, `HELP`)
SELECT 'NotaFiscalDevolucao', 'Devolução de Nota Fiscal', 'Wizard de devolução de NF com tributos'
WHERE NOT EXISTS (SELECT 1 FROM `AMB_FORM` WHERE `NOMEFORM` = 'NotaFiscalDevolucao');

INSERT INTO `AMB_USUARIO_AUTORIZA` (`USUARIO`, `PROGRAMA`, `DIREITOS`)
SELECT 999, 'NotaFiscalDevolucao', 'IAECSR'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `AMB_USUARIO_AUTORIZA` WHERE `USUARIO` = 999 AND `PROGRAMA` = 'NotaFiscalDevolucao');


-- 94. FAT_PARAMETRO: tipo de comissao de vendas (Comissao de Vendas)
-- =====================================================
-- 1 = Faturamento (AMB_USUARIO.COMISSAOFATURA / situacoes 6,3,9)
-- 2 = Recebimento (AMB_USUARIO.COMISSAORECEB) - escopo futuro
ALTER TABLE `FAT_PARAMETRO`
ADD COLUMN `TIPOCOMISSAO` int NOT NULL DEFAULT 1 COMMENT '1=Faturamento; 2=Recebimento';

-- 95. EST_UNIDADE — cadastro de unidades de medida (estoque)
-- =====================================================
CREATE TABLE IF NOT EXISTS `EST_UNIDADE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `UNIDADE` varchar(3) NOT NULL,
  `DESCRICAO` varchar(40) NOT NULL,
  `ATIVO` char(1) DEFAULT 'S',
  `USERINSERT` int(11) DEFAULT NULL,
  `DATEINSERT` timestamp NULL DEFAULT current_timestamp(),
  `USERCHANGE` int(11) DEFAULT NULL,
  `DATECHANGE` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_UNIDADE` (`UNIDADE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `EST_UNIDADE` (`UNIDADE`, `DESCRICAO`, `ATIVO`)
SELECT DISTINCT TRIM(`UNIDADE`), TRIM(`UNIDADE`), 'S'
FROM `EST_PRODUTO`
WHERE TRIM(`UNIDADE`) <> ''
  AND NOT EXISTS (
    SELECT 1 FROM `EST_UNIDADE` u WHERE u.`UNIDADE` = TRIM(`EST_PRODUTO`.`UNIDADE`)
  );

INSERT INTO `AMB_FORM` (`NOMEFORM`, `DESCRICAO`, `HELP`)
SELECT 'EstUnidade', 'ESTOQUE->Unidade', NULL
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `AMB_FORM` WHERE `NOMEFORM` = 'EstUnidade');

INSERT INTO `AMB_USUARIO_AUTORIZA` (`USUARIO`, `PROGRAMA`, `DIREITOS`)
SELECT 999, 'EstUnidade', 'IAECSR'
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM `AMB_USUARIO_AUTORIZA`
  WHERE `USUARIO` = 999 AND `PROGRAMA` = 'EstUnidade'
);


-- 96. INTEGRAÇÃO PROTIK — usuário portal (matrícula 2000)
-- =====================================================
-- NOME/SENHA → credenciais do php-login no Protik
-- SMTP       → URL da API Protik
-- EMAIL      → URL do front Protik
-- NOME é derivado do schema (admsis_maxifarma → maxifarma), para cada cliente.
-- Logins esperados: maxifarma, hiperfarma, requemaq, betonex, la, tork,
--                   telhagres, tratorraffa, bianco, ivemar, modena

SET @protik_login = REPLACE(DATABASE(), 'admsis_', '');
SET @protik_api   = 'https://protikserv.admsoftware.com.br:30006';
SET @protik_front = 'https://protik.admsoftware.com.br';

INSERT INTO `AMB_USUARIO` (
  `USUARIO`,
  `NOME`,
  `NOMEREDUZIDO`,
  `SENHA`,
  `SITUACAO`,
  `TIPO`,
  `GRUPO`,
  `MENUPRINCIPAL`,
  `EMPRESA`,
  `SMTP`,
  `EMAIL`
)
SELECT
  2000,
  @protik_login,
  'Portal Protik',
  'Cliente@123',
  'A',
  'Z',
  1000,
  'ALXCGF',
  1,
  @protik_api,
  @protik_front
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM `AMB_USUARIO` WHERE `USUARIO` = 2000
);

UPDATE `AMB_USUARIO`
SET
  `NOME` = @protik_login,
  `SMTP` = @protik_api,
  `EMAIL` = @protik_front,
  `SITUACAO` = 'A'
WHERE `USUARIO` = 2000
  AND (`NOME` IS NULL OR `NOME` = '' OR `NOME` = 'AJUSTAR_NOME_PROTIK' OR `NOME` = @protik_login);


-- 94. APURAÇÃO ASSISTIDA IBS/CBS - JULHO-2026
-- =====================================================
-- Ver script completo: bib/clientes_migracao_4_5/est_apuracao_cbs.sql

INSERT INTO `AMB_FORM` (`NOMEFORM`, `DESCRICAO`, `HELP`)
SELECT 'EstApuracaoCbs', 'ESTOQUE->Apuração Assistida IBS/CBS', 'Consulta débitos IBS/CBS via API da Receita Federal'
WHERE NOT EXISTS (SELECT 1 FROM `AMB_FORM` WHERE `NOMEFORM` = 'EstApuracaoCbs');

INSERT INTO `AMB_USUARIO_AUTORIZA` (`USUARIO`, `PROGRAMA`, `DIREITOS`)
SELECT 999, 'EstApuracaoCbs', 'IAECSR'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `AMB_USUARIO_AUTORIZA` WHERE `USUARIO` = 999 AND `PROGRAMA` = 'EstApuracaoCbs');
-- FIM DAS ALTERAÇÕES DOS ARQUIVOS DE ATUALIZAÇÃO

  