-- =====================================================
-- MÓDULO: Apuração Assistida IBS/CBS
-- Data: 14/07/2026
-- Refatorado: 17/07/2026 (modelagem por DF-e + eventos por chave)
-- =====================================================

-- 1. CREDENCIAIS DA API (client_id / client_secret / token)
CREATE TABLE IF NOT EXISTS `EST_APURACAO_CBS_CREDENCIAL` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CNPJ_BASE` varchar(8) NOT NULL COMMENT '8 primeiros caracteres alfanuméricos do CNPJ (NT 2026.004)',
  `CLIENT_ID` varchar(255) NOT NULL,
  `CLIENT_SECRET` text NOT NULL COMMENT 'Armazenado criptografado (AES-256-CBC)',
  `AMBIENTE` varchar(20) NOT NULL DEFAULT 'HOMOLOGACAO' COMMENT 'HOMOLOGACAO|PRODUCAO',
  `TOKEN` text DEFAULT NULL COMMENT 'Bearer criptografado (AES-256-CBC), mesmo padrão do CLIENT_SECRET',
  `TOKEN_EXPIRA_EM` datetime DEFAULT NULL,
  `WEBHOOK_URL` varchar(500) DEFAULT NULL COMMENT 'urlRetorno pública (HTTPS) onde a RF entrega o tíquete',
  `WEBHOOK_SECRET` varchar(100) DEFAULT NULL COMMENT 'Segredo para validar o POST do webhook',
  `USER_INSERT` int(11) DEFAULT NULL,
  `USER_UPDATE` int(11) DEFAULT NULL,
  `DT_INSERT` datetime DEFAULT CURRENT_TIMESTAMP,
  `DT_UPDATE` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_CNPJ_BASE_AMB` (`CNPJ_BASE`, `AMBIENTE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 2. HISTÓRICO DE REQUISIÇÕES (tíquetes)
CREATE TABLE IF NOT EXISTS `EST_APURACAO_CBS_HISTORICO` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CNPJ_BASE` varchar(8) NOT NULL,
  `TIQUETE` varchar(100) DEFAULT NULL,
  `WEBHOOK_URL` varchar(500) DEFAULT NULL,
  `STATUS` varchar(30) NOT NULL DEFAULT 'SOLICITADO' COMMENT 'SOLICITADO|AGUARDANDO_RETORNO|PROCESSANDO|DISPONIVEL|BAIXADO|ERRO|EXPIRADO',
  `HTTP_CODE` int(11) DEFAULT NULL,
  `MSG_RETORNO` text DEFAULT NULL,
  `DT_SOLICITACAO` datetime DEFAULT CURRENT_TIMESTAMP,
  `DT_DOWNLOAD` datetime DEFAULT NULL,
  `DT_EXPIRA_ARQUIVO` datetime DEFAULT NULL COMMENT 'Validade 24h do JSON',
  `USER_INSERT` int(11) DEFAULT NULL,
  `DT_INSERT` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `IDX_CNPJ_DT` (`CNPJ_BASE`, `DT_SOLICITACAO`),
  KEY `IDX_TIQUETE` (`TIQUETE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 3. DÉBITOS (DF-e) RETORNADOS PELA API - Nível 3 do JSON da RF
CREATE TABLE IF NOT EXISTS `EST_APURACAO_CBS_DEBITO` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ID_HISTORICO` int(11) NOT NULL,
  `TIPO_APURACAO` varchar(50) DEFAULT NULL COMMENT 'apuracaoCorrente|apuracaoAjuste|debitosExtemporaneos',
  `DATA_APURACAO` varchar(6) DEFAULT NULL COMMENT 'Formato AAAAMM',
  `CHAVE_DFE` varchar(44) NOT NULL COMMENT 'Chave de acesso de 44 posições',
  `MODELO_DFE` varchar(2) DEFAULT NULL,
  `NUMERO_DFE` varchar(20) DEFAULT NULL,
  `NI_EMITENTE` varchar(14) DEFAULT NULL COMMENT 'CNPJ/CPF alfanumérico do emitente',
  `NI_ADQUIRENTE` varchar(14) DEFAULT NULL COMMENT 'CNPJ/CPF alfanumérico do adquirente',
  `CNPJ_BASE` varchar(8) NOT NULL COMMENT 'CNPJ base da empresa consultada',
  `DATA_DFE_EMISSAO` datetime DEFAULT NULL,
  `DATA_DFE_AUTORIZACAO` datetime DEFAULT NULL COMMENT 'dataDfeAutorizacao',
  `DATA_DFE_REGISTRO` datetime DEFAULT NULL,
  `VALOR_CBS_TOTAL` decimal(18,2) DEFAULT NULL COMMENT 'Valor do débito principal',
  `VALOR_CBS_EXTINTO` decimal(18,2) DEFAULT NULL COMMENT 'Valor já pago/abatido',
  `VALOR_CBS_NAO_EXTINTO` decimal(18,2) DEFAULT NULL COMMENT 'Saldo em aberto',
  `VALOR_PRESCRITO` decimal(18,2) DEFAULT NULL COMMENT 'formasExtincao.prescricao (valor)',
  `DATA_PRESCRITO` datetime DEFAULT NULL COMMENT 'formasExtincao.prescricao (data)',
  `SITUACAO_DEBITO` varchar(50) DEFAULT NULL COMMENT 'Ex: Não Extinto, Aguardando Processamento, Cancelado',
  `PAPEL_EMPRESA` varchar(15) DEFAULT 'OUTRO' COMMENT 'EMITENTE|DESTINATARIO|OUTRO',
  `STATUS_EVENTO` varchar(20) DEFAULT 'PENDENTE' COMMENT 'PENDENTE|REGISTRADO|ERRO (controle interno de eventos)',
  `JSON_ORIGINAL` longtext DEFAULT NULL,
  `DIVERGENTE` char(1) DEFAULT 'N' COMMENT 'S=divergiu do download anterior (mesma chave)',
  `ID_DEBITO_ANTERIOR` int(11) DEFAULT NULL,
  `DT_INSERT` datetime DEFAULT CURRENT_TIMESTAMP,
  `DT_UPDATE` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `IDX_HISTORICO` (`ID_HISTORICO`),
  KEY `IDX_CHAVE` (`CHAVE_DFE`),
  KEY `IDX_PAPEL_SALDO` (`PAPEL_EMPRESA`, `VALOR_CBS_NAO_EXTINTO`),
  UNIQUE KEY `UK_CHAVE_HIST` (`CHAVE_DFE`, `ID_HISTORICO`),
  CONSTRAINT `FK_DEB_HIST` FOREIGN KEY (`ID_HISTORICO`)
    REFERENCES `EST_APURACAO_CBS_HISTORICO` (`ID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 4. FORMAS DE EXTINÇÃO - PAGAMENTOS / SPLIT (Nível 5 e 6 do JSON)
CREATE TABLE IF NOT EXISTS `EST_APURACAO_CBS_PGTO` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ID_DEBITO` int(11) NOT NULL,
  `NUMERO_DARF` varchar(17) DEFAULT NULL,
  `TIPO_PAGAMENTO` varchar(30) DEFAULT NULL COMMENT 'split|adquirente|contribuinte|responsavel',
  `DATA_ARRECADACAO` datetime DEFAULT NULL,
  `DATA_UTILIZACAO` datetime DEFAULT NULL,
  `VALOR_PRINCIPAL` decimal(18,2) DEFAULT NULL,
  `VALOR_MULTA` decimal(18,2) DEFAULT NULL,
  `VALOR_JUROS` decimal(18,2) DEFAULT NULL,
  `DT_INSERT` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `IDX_DEB_PGTO` (`ID_DEBITO`),
  CONSTRAINT `FK_PGTO_DEB` FOREIGN KEY (`ID_DEBITO`)
    REFERENCES `EST_APURACAO_CBS_DEBITO` (`ID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 5. FORMAS DE EXTINÇÃO - CRÉDITOS UTILIZADOS (Nível 5 e 6 do JSON)
CREATE TABLE IF NOT EXISTS `EST_APURACAO_CBS_CREDITO_UTILIZADO` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ID_DEBITO` int(11) NOT NULL,
  `TIPO_TRIBUTO` varchar(20) DEFAULT NULL COMMENT 'CBS|PISCOFINS',
  `CCLASS_CRED` varchar(50) DEFAULT NULL COMMENT 'Classificação do crédito (Básico, Presumido, etc.)',
  `ORIGEM` varchar(60) DEFAULT NULL COMMENT 'Origem do crédito (usado em creditosPISCOFINS)',
  `CHAVE_DFE_ORIGEM` varchar(44) DEFAULT NULL COMMENT 'Chave da nota que gerou este crédito',
  `MODELO_DFE_ORIGEM` varchar(2) DEFAULT NULL,
  `NUMERO_DFE_ORIGEM` varchar(20) DEFAULT NULL,
  `DATA_UTILIZACAO` datetime DEFAULT NULL,
  `VALOR_PRINCIPAL` decimal(18,2) DEFAULT NULL,
  `VALOR_MULTA` decimal(18,2) DEFAULT NULL,
  `VALOR_JUROS` decimal(18,2) DEFAULT NULL,
  `DT_INSERT` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `IDX_DEB_CRED` (`ID_DEBITO`),
  CONSTRAINT `FK_CRED_DEB` FOREIGN KEY (`ID_DEBITO`)
    REFERENCES `EST_APURACAO_CBS_DEBITO` (`ID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 6. EVENTOS FISCAIS EMITIDOS POR CHAVE (aceite, apropriação de crédito, etc.)
--    Vinculado à CHAVE_DFE para sobreviver a re-downloads (DELETE de débitos).
CREATE TABLE IF NOT EXISTS `EST_APURACAO_CBS_EVENTO` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CHAVE_DFE` varchar(44) NOT NULL COMMENT 'Chave de acesso da nota referenciada',
  `ID_DEBITO` int(11) DEFAULT NULL COMMENT 'Débito interno (pode ser removido em re-download)',
  `TP_EVENTO` varchar(6) NOT NULL COMMENT 'Ex.: 211128, 112110',
  `ORIGEM` varchar(10) NOT NULL DEFAULT 'LOCAL' COMMENT 'LOCAL=emitido por nós | RF=retornado na apuração',
  `PAPEL` varchar(15) DEFAULT NULL COMMENT 'EMITENTE|DESTINATARIO',
  `DESCRICAO` varchar(120) DEFAULT NULL COMMENT 'Rótulo do evento',
  `OBSERVACAO` text DEFAULT NULL,
  `PROTOCOLO` varchar(100) DEFAULT NULL,
  `HTTP_CODE` int(11) DEFAULT NULL,
  `JSON_ENVIO` longtext DEFAULT NULL,
  `JSON_RETORNO` longtext DEFAULT NULL,
  `MSG_RETORNO` text DEFAULT NULL,
  `STATUS` varchar(20) DEFAULT 'REGISTRADO' COMMENT 'REGISTRADO|ENVIADO|SUCESSO|ERRO|PENDENTE_API',
  `USER_INSERT` int(11) DEFAULT NULL,
  `DT_INSERT` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `IDX_EVENTO_CHAVE` (`CHAVE_DFE`),
  KEY `IDX_EVENTO_DEBITO` (`ID_DEBITO`),
  KEY `IDX_EVENTO_TP` (`TP_EVENTO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 7. LOG DE RECEBIMENTO DO WEBHOOK (auditoria do beta)
CREATE TABLE IF NOT EXISTS `EST_APURACAO_CBS_WEBHOOK_LOG` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CNPJ_BASE` varchar(8) DEFAULT NULL,
  `ORIGEM_IP` varchar(45) DEFAULT NULL,
  `HEADERS` text DEFAULT NULL,
  `PAYLOAD` longtext DEFAULT NULL,
  `TIQUETE` varchar(100) DEFAULT NULL,
  `PROCESSADO` char(1) DEFAULT 'N' COMMENT 'S=processado com sucesso | N=falha/ignorado',
  `MSG` text DEFAULT NULL,
  `DT_INSERT` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `IDX_WHL_CNPJ` (`CNPJ_BASE`),
  KEY `IDX_WHL_TIQUETE` (`TIQUETE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- =====================================================
-- MIGRAÇÃO PARA INSTALAÇÕES EXISTENTES (executar apenas
-- se as tabelas já existiam antes destas colunas).
-- MySQL não suporta ADD COLUMN IF NOT EXISTS: rode manualmente
-- e ignore erros de "Duplicate column".
-- =====================================================
-- ALTER TABLE `EST_APURACAO_CBS_CREDENCIAL`
--   ADD COLUMN `WEBHOOK_SECRET` varchar(100) DEFAULT NULL AFTER `WEBHOOK_URL`;
-- ALTER TABLE `EST_APURACAO_CBS_DEBITO`
--   ADD COLUMN `DATA_DFE_AUTORIZACAO` datetime DEFAULT NULL AFTER `DATA_DFE_EMISSAO`,
--   ADD COLUMN `VALOR_PRESCRITO` decimal(18,2) DEFAULT NULL AFTER `VALOR_CBS_NAO_EXTINTO`,
--   ADD COLUMN `DATA_PRESCRITO` datetime DEFAULT NULL AFTER `VALOR_PRESCRITO`;
-- ALTER TABLE `EST_APURACAO_CBS_CREDITO_UTILIZADO`
--   ADD COLUMN `ORIGEM` varchar(60) DEFAULT NULL AFTER `CCLASS_CRED`,
--   ADD COLUMN `MODELO_DFE_ORIGEM` varchar(2) DEFAULT NULL AFTER `CHAVE_DFE_ORIGEM`,
--   ADD COLUMN `NUMERO_DFE_ORIGEM` varchar(20) DEFAULT NULL AFTER `MODELO_DFE_ORIGEM`;
-- ALTER TABLE `EST_APURACAO_CBS_EVENTO`
--   ADD COLUMN `ORIGEM` varchar(10) NOT NULL DEFAULT 'LOCAL' AFTER `TP_EVENTO`;

-- 8. DIREITOS DE ACESSO
INSERT INTO `AMB_FORM` (`NOMEFORM`, `DESCRICAO`, `HELP`)
SELECT 'EstApuracaoCbs', 'ESTOQUE->Apuração Assistida IBS/CBS', 'Consulta débitos IBS/CBS via API da Receita Federal'
WHERE NOT EXISTS (SELECT 1 FROM `AMB_FORM` WHERE `NOMEFORM` = 'EstApuracaoCbs');

INSERT INTO `AMB_USUARIO_AUTORIZA` (`USUARIO`, `PROGRAMA`, `DIREITOS`)
SELECT 999, 'EstApuracaoCbs', 'IAECSR'
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM `AMB_USUARIO_AUTORIZA`
  WHERE `USUARIO` = 999 AND `PROGRAMA` = 'EstApuracaoCbs'
);
